# Generated by Django 5.2.8 on 2025-11-27 07:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分類名稱')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設分類')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '圖片分類',
                'verbose_name_plural': '圖片分類',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='圖片標題')),
                ('description', models.TextField(blank=True, verbose_name='圖片描述')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/', verbose_name='圖片檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='ImageGallery.imagecategory', verbose_name='分類')),
            ],
            options={
                'verbose_name': '圖片',
                'verbose_name_plural': '圖片',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='評分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='評分時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ImageGallery.image', verbose_name='圖片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_ratings', to=settings.AUTH_USER_MODEL, verbose_name='評分者')),
            ],
            options={
                'verbose_name': '圖片評分',
                'verbose_name_plural': '圖片評分',
                'ordering': ['-created_at'],
                'unique_together': {('image', 'user')},
            },
        ),
    ]
