# Generated by Django 5.2.8 on 2025-11-27 07:03

from django.db import migrations

def create_default_categories(apps, schema_editor):
    ImageCategory = apps.get_model('ImageGallery', 'ImageCategory')
    
    default_categories = [
        '自製',
        'AI產生',
        '網路下載'
    ]
    
    for name in default_categories:
        ImageCategory.objects.get_or_create(
            name=name,
            defaults={'is_default': True}
        )

def remove_default_categories(apps, schema_editor):
    ImageCategory = apps.get_model('ImageGallery', 'ImageCategory')
    
    default_categories = [
        '自製',
        'AI產生',
        '網路下載'
    ]
    
    ImageCategory.objects.filter(name__in=default_categories, is_default=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('ImageGallery', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
