# Generated by Django 5.2.8 on 2025-12-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageGallery', '0002_create_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='地點'),
        ),
        migrations.AddField(
            model_name='image',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='拍攝時間'),
        ),
    ]
