# Generated by Django 4.2.20 on 2026-02-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名稱')),
                ('city', models.CharField(max_length=100, verbose_name='縣市')),
                ('remain_capacity', models.FloatField(blank=True, null=True, verbose_name='B1~B7剩餘填埋量')),
                ('coord_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='轉換狀態')),
                ('site_type', models.CharField(max_length=100, verbose_name='類型')),
                ('control_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='流向編號')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='經度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='面積')),
                ('max_capacity', models.FloatField(blank=True, null=True, verbose_name='B1~B7核准填埋量')),
                ('apply_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='申報日期')),
            ],
            options={
                'verbose_name': '土方暫置場',
                'verbose_name_plural': '土方暫置場',
            },
        ),
    ]
