# Generated by Django 4.2.20 on 2026-02-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soilmove', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilmove',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='資料更新時間'),
        ),
    ]
