# Generated by Django 5.2.9 on 2026-02-23 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rnd', '研發專案'), ('market', '跳蚤市場'), ('gossip', '七嘴八舌')], max_length=10, verbose_name='類型')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名發布')),
                ('category', models.CharField(blank=True, choices=[('bug', 'Bug報修'), ('feature', '功能建議'), ('announcement', '最新公告')], max_length=20, verbose_name='分類')),
                ('status', models.CharField(blank=True, max_length=20, verbose_name='狀態')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10, verbose_name='優先度')),
                ('package_name', models.CharField(blank=True, max_length=100, verbose_name='指定套件')),
                ('problem_type', models.CharField(blank=True, max_length=100, verbose_name='問題類型')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='價格')),
                ('price_label', models.CharField(blank=True, max_length=50, verbose_name='價格標籤')),
                ('condition', models.CharField(blank=True, choices=[('new', '全新'), ('90', '九成新'), ('80', '八成新'), ('70', '七成新'), ('functional', '功能正常但外觀舊'), ('broken', '故障/零件機')], max_length=20, verbose_name='物品狀況')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lhawish/posts/%Y/%m/', verbose_name='圖片')),
                ('visibility', models.CharField(choices=[('all', '全部門'), ('deputy_up', '僅副主管以上'), ('manager_only', '僅主管可見')], default='all', max_length=20, verbose_name='可見對象')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '貼文',
                'verbose_name_plural': '貼文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_official', models.BooleanField(default=False, verbose_name='官方回覆')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='LHAWish.post', verbose_name='貼文')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False, verbose_name='已按讚')),
                ('saved', models.BooleanField(default=False, verbose_name='已收藏')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='LHAWish.post', verbose_name='貼文')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_interactions', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '貼文互動',
                'verbose_name_plural': '貼文互動',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
