# Generated by Django 5.2.9 on 2026-02-23 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='提議標題')),
                ('content', models.TextField(verbose_name='提議內容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名提議')),
                ('display_name', models.CharField(blank=True, help_text='留空則顯示真實姓名，填入則以此名稱顯示', max_length=50, verbose_name='顯示名稱')),
                ('assigned_group', models.CharField(choices=[('engineering', '工程組'), ('urban_planning', '國土城規組'), ('sustainability', '國土永續中心'), ('other', '其他組'), ('management', '部門主管/副主管')], max_length=30, verbose_name='指定執行組別')),
                ('status', models.CharField(choices=[('endorsing', '附議中'), ('established', '已成案'), ('withdrawn', '已撤案'), ('responded', '已回應')], default='endorsing', max_length=20, verbose_name='狀態')),
                ('endorsement_threshold', models.PositiveIntegerField(default=50, help_text='達到此數量即自動成案', verbose_name='附議門檻')),
                ('withdraw_reason', models.TextField(blank=True, verbose_name='撤案理由')),
                ('response_content', models.TextField(blank=True, verbose_name='回應內容')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='回應時間')),
                ('deadline', models.DateTimeField(blank=True, help_text='成案後自動設為 +2 個月', null=True, verbose_name='回應期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_petitions', to=settings.AUTH_USER_MODEL, verbose_name='提議人')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lhawish_responses', to=settings.AUTH_USER_MODEL, verbose_name='回應人')),
            ],
            options={
                'verbose_name': '園路願望提議',
                'verbose_name_plural': '園路願望提議',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetitionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_petition_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petition_comments', to='LHAWish.petition', verbose_name='提議')),
            ],
            options={
                'verbose_name': '提議留言',
                'verbose_name_plural': '提議留言',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='附議時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_endorsements', to=settings.AUTH_USER_MODEL, verbose_name='附議人')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='LHAWish.petition', verbose_name='提議')),
            ],
            options={
                'verbose_name': '附議',
                'verbose_name_plural': '附議',
                'unique_together': {('petition', 'user')},
            },
        ),
    ]
