# Generated by Django 5.2.9 on 2026-02-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0002_petition_petitioncomment_endorsement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='assigned_group',
            field=models.CharField(blank=True, choices=[('engineering', '工程組'), ('urban_planning', '國土城規組'), ('sustainability', '國土永續中心'), ('other', '其他組'), ('management', '部門主管/副主管')], max_length=30, verbose_name='指定組別'),
        ),
    ]
