# Generated by Django 5.2.9 on 2026-02-25 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0003_post_assigned_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endorsement_threshold', models.PositiveIntegerField(default=50, verbose_name='附議成案門檻')),
                ('package_choices', models.JSONField(blank=True, default=list, help_text='["套件A","套件B"]', verbose_name='研發專案套件清單')),
                ('group_choices', models.JSONField(blank=True, default=list, help_text='[{"value":"engineering","label":"工程組"}]', verbose_name='指定組別清單')),
                ('manager_emails', models.JSONField(blank=True, default=list, help_text='["email@example.com"]', verbose_name='主管信箱名單')),
                ('board_admins', models.JSONField(blank=True, default=dict, help_text='{"petition":[1,2],"rnd":[3]}', verbose_name='各版板主')),
            ],
            options={
                'verbose_name': '系統設定',
                'verbose_name_plural': '系統設定',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名留言'),
        ),
        migrations.AddField(
            model_name='petition',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='已修改內文'),
        ),
        migrations.AddField(
            model_name='petitioncomment',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名留言'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='assigned_group',
            field=models.CharField(blank=True, choices=[('engineering', '工程組'), ('urban_planning', '國土城規組'), ('sustainability', '國土永續中心'), ('other', '其他組'), ('management', '部門主管/副主管')], max_length=30, verbose_name='指定執行組別'),
        ),
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(blank=True, max_length=100, verbose_name='物品狀況'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='按讚時間')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='LHAWish.comment', verbose_name='貼文留言')),
                ('petition_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='LHAWish.petitioncomment', verbose_name='提議留言')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '留言按讚',
                'verbose_name_plural': '留言按讚',
            },
        ),
        migrations.CreateModel(
            name='PetitionSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='LHAWish.petition', verbose_name='提議')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lhawish_petition_saves', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '提議收藏',
                'verbose_name_plural': '提議收藏',
                'unique_together': {('petition', 'user')},
            },
        ),
    ]
