# Generated by Django 5.2.9 on 2026-02-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0004_siteconfig_comment_is_anonymous_petition_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='已編輯'),
        ),
        migrations.AddField(
            model_name='petitioncomment',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='已編輯'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='存放 base64 或圖片路徑清單', verbose_name='多張圖片'),
        ),
    ]
