# Generated by Django 5.2.9 on 2026-02-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0005_comment_is_edited_petitioncomment_is_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitioncomment',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='管理者留言'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='status',
            field=models.CharField(choices=[('endorsing', '附議中'), ('established', '已成案'), ('withdrawn', '已撤案'), ('responded', '已回應'), ('hidden', '已隱藏')], default='endorsing', max_length=20, verbose_name='狀態'),
        ),
    ]
