# Generated by Django 5.2.9 on 2026-02-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0006_petitioncomment_is_official_alter_petition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='assigned_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='指定執行組別'),
        ),
    ]
