# Generated by Django 5.2.9 on 2026-02-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0007_alter_petition_assigned_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='assigned_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='指定組別'),
        ),
    ]
