# Generated by Django 5.2.9 on 2026-02-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0008_alter_post_assigned_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='post',
            name='visibility',
        ),
    ]
