# Generated by Django 5.2.9 on 2026-03-02 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0009_remove_post_priority_remove_post_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回應時間'),
        ),
        migrations.AddField(
            model_name='post',
            name='response_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lhawish_post_responses', to=settings.AUTH_USER_MODEL, verbose_name='回應人'),
        ),
        migrations.AddField(
            model_name='post',
            name='response_content',
            field=models.TextField(blank=True, verbose_name='回應內容'),
        ),
    ]
