# Generated by Django 5.2.9 on 2026-03-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0010_post_response_at_post_response_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_name',
            field=models.CharField(blank=True, help_text='留空則顯示預設的匿名，填入則以此名稱顯示', max_length=50, verbose_name='顯示名稱'),
        ),
    ]
