# Generated by Django 5.2.9 on 2026-03-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0011_post_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rnd_project',
            field=models.CharField(blank=True, max_length=100, verbose_name='研發案'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='rnd_project_choices',
            field=models.JSONField(blank=True, default=list, help_text='[{"value":"proj_a","label":"研發案A"}]', verbose_name='研發案清單'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='board_admins',
            field=models.JSONField(blank=True, default=dict, help_text='{"petition":[{"uid":1}],"rnd":[{"uid":2}]}', verbose_name='各版板主'),
        ),
    ]
