# Generated by Django 5.2.9 on 2026-03-04 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0012_post_rnd_project_siteconfig_rnd_project_choices_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='project_admins',
            field=models.ManyToManyField(blank=True, help_text='擁有許願池所有設定分頁的檢視與編輯權限', related_name='lhawish_admin_configs', to=settings.AUTH_USER_MODEL, verbose_name='專案管理員'),
        ),
    ]
