# Generated by Django 5.2.9 on 2026-03-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0013_add_project_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='old_version_url',
            field=models.URLField(blank=True, verbose_name='舊版網址'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='show_old_version',
            field=models.BooleanField(default=False, verbose_name='顯示回舊版按鈕'),
        ),
    ]
