# Generated by Django 5.2.9 on 2026-03-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LHAWish', '0014_siteconfig_old_version_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='old_version_text',
            field=models.CharField(default='回舊版', max_length=50, verbose_name='回舊版按鈕文字'),
        ),
    ]
