# Generated by Django 5.2.12 on 2026-03-09 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='review_feedback/json/', verbose_name='JSON 檔案')),
                ('original_filename', models.CharField(max_length=512, verbose_name='原始檔名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': '比對結果檔',
                'verbose_name_plural': '比對結果檔',
                'ordering': ['original_filename'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='專案名稱')),
                ('description', models.TextField(blank=True, default='', verbose_name='專案說明')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='review_feedback/pdfs/', verbose_name='PDF 報告書')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '專案',
                'verbose_name_plural': '專案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.TextField(verbose_name='減碳策略名稱')),
                ('excerpt_text', models.TextField(verbose_name='文字摘錄')),
                ('source_page', models.CharField(blank=True, default='', max_length=20, verbose_name='來源頁碼')),
                ('reasoning', models.TextField(blank=True, default='', verbose_name='AI 推論說明')),
                ('is_match', models.BooleanField(default=False, verbose_name='是否匹配')),
                ('arbitration_status', models.CharField(blank=True, default='', max_length=50, verbose_name='仲裁狀態')),
                ('arbitration_note', models.JSONField(blank=True, null=True, verbose_name='仲裁備註')),
                ('final_decision_class', models.CharField(blank=True, default='', max_length=255, verbose_name='最終判定分類')),
                ('char_start_pos', models.IntegerField(blank=True, null=True, verbose_name='字元起始位置')),
                ('char_end_pos', models.IntegerField(blank=True, null=True, verbose_name='字元結束位置')),
                ('comparison_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='review_feedback.comparisonfile', verbose_name='所屬比對檔')),
            ],
            options={
                'verbose_name': '比對結果',
                'verbose_name_plural': '比對結果',
                'ordering': ['source_page', 'char_start_pos'],
            },
        ),
        migrations.AddField(
            model_name='comparisonfile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_files', to='review_feedback.project', verbose_name='所屬專案'),
        ),
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='判定是否正確')),
                ('feedback_reason', models.TextField(blank=True, default='', verbose_name='回饋說明')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='審查時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_feedbacks', to='review_feedback.comparisonentry', verbose_name='比對結果')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='審查者')),
            ],
            options={
                'verbose_name': '審查回饋',
                'verbose_name_plural': '審查回饋',
                'ordering': ['-reviewed_at'],
            },
        ),
    ]
