# Generated by Django 5.2.9 on 2026-01-06 03:54

import PatentRegistry.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_number', models.CharField(max_length=50, verbose_name='計畫編號')),
                ('outsource_number', models.CharField(blank=True, max_length=50, verbose_name='委外編號')),
                ('item_number', models.PositiveIntegerField(default=1, verbose_name='項次')),
                ('name', models.CharField(max_length=255, verbose_name='申請專利項目名稱')),
                ('category', models.CharField(choices=[('INVENTION', '發明專利'), ('UTILITY_MODEL', '新型專利'), ('DESIGN', '設計專利')], max_length=20, verbose_name='申請專利項目類別')),
                ('patent_firm', models.CharField(max_length=200, verbose_name='委託專利事務所名稱')),
                ('firm_case_number', models.CharField(blank=True, max_length=50, verbose_name='事務所案號')),
                ('status', models.CharField(choices=[('PENDING', '申請中'), ('APPROVED', '通過'), ('REJECTED', '不通過')], default='PENDING', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_applications', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '專利申請',
                'verbose_name_plural': '專利申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantedPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_number', models.CharField(max_length=50, verbose_name='專利編號')),
                ('patent_name', models.CharField(max_length=255, verbose_name='專利名稱')),
                ('patent_period', models.CharField(blank=True, max_length=50, verbose_name='專利期間')),
                ('description', models.TextField(blank=True, verbose_name='專利簡述')),
                ('start_date', models.DateField(verbose_name='專利起始年月')),
                ('end_date', models.DateField(verbose_name='專利結束年月')),
                ('certificate', models.FileField(blank=True, null=True, upload_to=PatentRegistry.models.patent_certificate_path, verbose_name='專利證書')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='取得時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='granted_patent', to='PatentRegistry.patentapplication', verbose_name='專利申請')),
            ],
            options={
                'verbose_name': '已取得專利',
                'verbose_name_plural': '已取得專利',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='PatentRebuttal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rebuttal_type', models.CharField(choices=[('FIRST', '初次答辯'), ('SECOND', '二次答辯'), ('THIRD', '三次答辯'), ('OTHER', '其他答辯')], max_length=20, verbose_name='答辯類別')),
                ('document_date', models.DateField(verbose_name='答辯單據日期')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='費用')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuttals', to='PatentRegistry.patentapplication', verbose_name='專利申請')),
            ],
            options={
                'verbose_name': '答辯記錄',
                'verbose_name_plural': '答辯記錄',
                'ordering': ['document_date'],
            },
        ),
        migrations.CreateModel(
            name='PatentAnnuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('write_off_plan_number', models.CharField(max_length=50, verbose_name='核銷計畫編號')),
                ('write_off_date', models.DateField(verbose_name='核銷年月')),
                ('year', models.PositiveIntegerField(verbose_name='核銷年度')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patent_annuities', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('granted_patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annuities', to='PatentRegistry.grantedpatent', verbose_name='已取得專利')),
            ],
            options={
                'verbose_name': '專利年費核銷',
                'verbose_name_plural': '專利年費核銷',
                'ordering': ['-year', '-write_off_date'],
                'unique_together': {('granted_patent', 'year')},
            },
        ),
    ]
