# Generated by Django 5.2.9 on 2026-01-06 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatentRegistry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patentapplication',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公開'),
        ),
        migrations.CreateModel(
            name='PatentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='設定時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patent_admins', to=settings.AUTH_USER_MODEL, verbose_name='設定者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patent_admin', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '專利管理員',
                'verbose_name_plural': '專利管理員',
                'ordering': ['-created_at'],
            },
        ),
    ]
