# Generated by Django 5.2.9 on 2026-01-08 06:46

import PatentRegistry.models
import SinoFile.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatentRegistry', '0002_patentapplication_is_public_patentadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantedpatent',
            name='certificate',
            field=SinoFile.fields.SinoFileField(blank=True, null=True, upload_to=PatentRegistry.models.patent_certificate_path, verbose_name='專利證書'),
        ),
    ]
