# Generated by Django 4.2.14 on 2024-10-24 07:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('SinoArchive', '0001_initial'), ('SinoArchive', '0002_auto_20190521_1621'), ('SinoArchive', '0003_auto_20190521_1629'), ('SinoArchive', '0004_auto_20190522_1024'), ('SinoArchive', '0005_auto_20190522_1058'), ('SinoArchive', '0006_auto_20190523_0956'), ('SinoArchive', '0007_auto_20190806_0857'), ('SinoArchive', '0008_auto_20190806_0957'), ('SinoArchive', '0009_archivefolder_has_files'), ('SinoArchive', '0010_auto_20200925_1710'), ('SinoArchive', '0011_alter_archivefolder_id'), ('SinoArchive', '0012_alter_archivefolder_id')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderName', models.CharField(blank=True, max_length=255, null=True, verbose_name='資料夾名稱')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('fulled', models.BooleanField(default=False, verbose_name='已滿')),
                ('fulled_at', models.DateTimeField(blank=True, null=True)),
                ('totalSize', models.BigIntegerField(default=0, verbose_name='總容量')),
                ('has_files', models.BooleanField(default=True, verbose_name='還有檔案')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=500, verbose_name='原始路徑')),
                ('ext', models.CharField(max_length=255, verbose_name='副檔名')),
                ('size', models.BigIntegerField(verbose_name='容量')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filesInFolder', to='SinoArchive.archivefolder', verbose_name='典藏資料夾')),
                ('processed', models.BooleanField(default=False, verbose_name='已處理')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('process_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
