# Generated by Django 5.2.8 on 2025-12-03 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='資料夾名稱')),
                ('total_size', models.BigIntegerField(default=0, verbose_name='總容量')),
                ('fulled', models.BooleanField(default=False, verbose_name='已滿')),
                ('fulled_at', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('has_files', models.BooleanField(default=True, verbose_name='還有檔案')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=500, verbose_name='原始路徑')),
                ('ext', models.CharField(max_length=255, verbose_name='副檔名')),
                ('size', models.BigIntegerField(verbose_name='容量')),
                ('processed', models.BooleanField(default=False, verbose_name='已處理')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('process_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_in_folders', to='SinoArchive.archivefolder', verbose_name='典藏資料夾')),
            ],
        ),
    ]
