# Generated by Django 5.2.8 on 2025-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SinoArchive', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivefolder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
