# Generated by Django 5.2.11 on 2026-02-25 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255, verbose_name='搜尋關鍵字')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='起始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('topic_words', models.TextField(blank=True, verbose_name='主題詞')),
                ('stop_words', models.TextField(blank=True, verbose_name='停用詞')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查詢時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '搜尋紀錄',
                'verbose_name_plural': '搜尋紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
