# Generated by Django 5.2.8 on 2025-12-02 10:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='課程標題')),
                ('description', models.TextField(verbose_name='課程說明')),
                ('course_datetime', models.DateTimeField(verbose_name='上課時間')),
                ('registration_start', models.DateTimeField(verbose_name='報名開始時間')),
                ('registration_end', models.DateTimeField(verbose_name='報名截止時間')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='courses/pdfs/%Y/%m/', verbose_name='PDF 附件')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='留空表示不限制人數', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='報名人數上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='下載時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_downloads', to='CourseRegistration.course', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_downloads', to=settings.AUTH_USER_MODEL, verbose_name='下載者')),
            ],
            options={
                'verbose_name': 'PDF 下載記錄',
                'verbose_name_plural': 'PDF 下載記錄',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='報名時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='CourseRegistration.course', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL, verbose_name='報名者')),
            ],
            options={
                'verbose_name': '報名記錄',
                'verbose_name_plural': '報名記錄',
                'ordering': ['registered_at'],
                'unique_together': {('course', 'user')},
            },
        ),
    ]
