# Generated by Django 5.2.8 on 2025-12-03 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRegistration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, help_text='選填，可事後編輯', max_length=100, verbose_name='講師姓名'),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, help_text='選填，可事後編輯', max_length=200, verbose_name='課程地點'),
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='CourseRegistration.course', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_comments', to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '課程留言',
                'verbose_name_plural': '課程留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
