# Generated by Django 5.2.9 on 2026-01-08 06:46

import SinoFile.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRegistration', '0002_course_instructor_name_course_location_coursecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf_file',
            field=SinoFile.fields.SinoFileField(blank=True, null=True, upload_to='courses/pdfs/%Y/%m/', verbose_name='PDF 附件'),
        ),
    ]
