# Generated by Django 5.2.11 on 2026-02-05 03:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='類型名稱')),
                ('icon', models.CharField(blank=True, default='bi-tag', max_length=50, verbose_name='圖示')),
                ('color', models.CharField(blank=True, default='#6c757d', max_length=20, verbose_name='顏色')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設類型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '支出類型',
                'verbose_name_plural': '支出類型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='參與者名稱')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '參與者',
                'verbose_name_plural': '參與者',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='日期')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='時間')),
                ('item_name', models.CharField(max_length=200, verbose_name='品項名稱')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='金額')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='ExpenseTracker.expensecategory', verbose_name='類型')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='ExpenseTracker.participant', verbose_name='付款人')),
            ],
            options={
                'verbose_name': '記帳紀錄',
                'verbose_name_plural': '記帳紀錄',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='應分攤金額')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='ExpenseTracker.expense', verbose_name='關聯記帳')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to='ExpenseTracker.participant', verbose_name='分攤者')),
            ],
            options={
                'verbose_name': '費用分攤',
                'verbose_name_plural': '費用分攤',
                'unique_together': {('expense', 'participant')},
            },
        ),
    ]
