# Generated by Django 5.2.10 on 2026-03-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundationExcavation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, default='Default Project', max_length=100, verbose_name='計畫編號')),
                ('bridge_name', models.CharField(db_index=True, default='Default Bridge', max_length=100, verbose_name='橋梁名稱')),
                ('bridge_id', models.CharField(max_length=50, verbose_name='基礎標識')),
                ('column_base_el', models.FloatField(verbose_name='柱底EL (column_base_el)')),
                ('h1_thickness', models.FloatField(verbose_name='版厚 (h1_thickness)')),
                ('c_pc_thickness', models.FloatField(verbose_name='打底PC (c_pc_thickness)')),
                ('B1', models.FloatField(verbose_name='B1')),
                ('B2', models.FloatField(verbose_name='B2')),
                ('L1', models.FloatField(verbose_name='L1')),
                ('L2', models.FloatField(verbose_name='L2')),
                ('el_l1_start', models.FloatField(verbose_name='L1起點地表EL')),
                ('el_l1_end', models.FloatField(verbose_name='L1終點地表EL')),
                ('el_l2_start', models.FloatField(verbose_name='L2起點地表EL')),
                ('el_l2_end', models.FloatField(verbose_name='L2終點地表EL')),
                ('el_b1_start', models.FloatField(verbose_name='B1起點地表EL')),
                ('el_b1_end', models.FloatField(verbose_name='B1終點地表EL')),
                ('el_b2_start', models.FloatField(verbose_name='B2起點地表EL')),
                ('el_b2_end', models.FloatField(verbose_name='B2終點地表EL')),
                ('offset_dist', models.FloatField(default=0.8, verbose_name='各階支撐退縮距離')),
                ('d1_manual', models.FloatField(default=0.5, verbose_name='強制指定第一階支撐與地表之最小間距')),
                ('excavation_plan', models.CharField(blank=True, max_length=100, null=True, verbose_name='開挖平面')),
                ('excavation_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='開挖剖面')),
                ('skew_angle', models.FloatField(default=0.0, verbose_name='夾角')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('needs_review', models.BooleanField(default=False, verbose_name='資料更新需檢視')),
            ],
            options={
                'verbose_name': '基礎開挖參數',
                'verbose_name_plural': '基礎開挖參數',
                'ordering': ['project_code', 'bridge_name', 'bridge_id'],
                'unique_together': {('project_code', 'bridge_name', 'bridge_id')},
            },
        ),
    ]
