# Generated by Django 5.2.9 on 2026-01-09 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_announcements', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_extension', models.CharField(max_length=20, verbose_name='分機')),
                ('project_number', models.CharField(max_length=100, verbose_name='計畫編號')),
                ('reason', models.TextField(verbose_name='申請理由')),
                ('usage_start_datetime', models.DateTimeField(verbose_name='使用開始時間')),
                ('usage_end_datetime', models.DateTimeField(verbose_name='使用結束時間')),
                ('location', models.CharField(max_length=200, verbose_name='地點')),
                ('notes', models.TextField(blank=True, verbose_name='其他說明')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '已核准'), ('rejected', '已拒絕'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('review_datetime', models.DateTimeField(blank=True, null=True, verbose_name='簽核時間')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='拒絕理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_reservations', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_drone_reservations', to=settings.AUTH_USER_MODEL, verbose_name='簽核人')),
            ],
            options={
                'verbose_name': '無人機預約',
                'verbose_name_plural': '無人機預約',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DroneReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drone_reviewer_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '簽核人（飛手）',
                'verbose_name_plural': '簽核人（飛手）',
            },
        ),
    ]
