# Generated by Django 5.2.9 on 2026-01-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-is_pinned', '-updated_at'], 'verbose_name': '公告', 'verbose_name_plural': '公告'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置頂'),
        ),
    ]
