# Generated by Django 5.2.9 on 2026-01-09 03:11

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0002_alter_announcement_options_announcement_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='內容'),
        ),
    ]
