# Generated by Django 5.2.9 on 2026-01-09 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0003_alter_announcement_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dronereservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='取消理由'),
        ),
        migrations.AddField(
            model_name='dronereviewer',
            name='can_manage_reviewers',
            field=models.BooleanField(default=False, verbose_name='可管理簽核人'),
        ),
        migrations.AddField(
            model_name='dronereviewer',
            name='receive_email',
            field=models.BooleanField(default=True, verbose_name='接收郵件通知'),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_subtitle', models.CharField(default='園區無人機使用預約系統', max_length=200, verbose_name='Banner 副標題')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最後更新者')),
            ],
            options={
                'verbose_name': '網站設定',
                'verbose_name_plural': '網站設定',
            },
        ),
    ]
