# Generated by Django 5.2.9 on 2026-02-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0004_dronereservation_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('new_application', '新申請待審核通知'), ('approved', '核准通知'), ('rejected', '拒絕通知'), ('cancelled', '取消通知'), ('time_changed', '時間變更通知')], max_length=30, unique=True, verbose_name='郵件類型')),
                ('subject_template', models.CharField(max_length=200, verbose_name='郵件主旨模板')),
                ('body_template', models.TextField(verbose_name='郵件內容模板')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '郵件模板',
                'verbose_name_plural': '郵件模板',
            },
        ),
    ]
