# Generated by Django 5.2.9 on 2026-02-09 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0005_emailtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_date', models.DateField(verbose_name='任務日期')),
                ('project_number', models.CharField(max_length=100, verbose_name='計畫編號')),
                ('project_short_name', models.CharField(max_length=100, verbose_name='計畫簡稱')),
                ('location_name', models.CharField(max_length=200, verbose_name='任務地點')),
                ('latitude', models.FloatField(help_text='例如：25.0478', verbose_name='緯度')),
                ('longitude', models.FloatField(help_text='例如：121.5319', verbose_name='經度')),
                ('mission_description', models.TextField(verbose_name='任務說明')),
                ('drone_payload', models.CharField(max_length=200, verbose_name='無人機/酬載')),
                ('result_location', models.CharField(help_text='檔案路徑或雲端連結', max_length=500, verbose_name='成果存放位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mission_records', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piloted_missions', to=settings.AUTH_USER_MODEL, verbose_name='任務飛手')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_records', to='DroneReservation.dronereservation', verbose_name='關聯預約單')),
            ],
            options={
                'verbose_name': '飛行任務紀錄',
                'verbose_name_plural': '飛行任務紀錄',
                'ordering': ['-mission_date', '-created_at'],
            },
        ),
    ]
