# Generated by Django 5.2.9 on 2026-02-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0006_missionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionrecord',
            name='pilot',
            field=models.CharField(default='', help_text='輸入飛手姓名', max_length=100, verbose_name='任務飛手'),
        ),
    ]
