# Generated by Django 5.2.9 on 2026-02-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0007_alter_missionrecord_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionrecord',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='結束時間'),
        ),
        migrations.AddField(
            model_name='missionrecord',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
    ]
