# Generated by Django 5.2.9 on 2026-02-10 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0008_missionrecord_end_time_missionrecord_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionrecord',
            options={'ordering': ['-mission_start_date', '-created_at'], 'verbose_name': '飛行任務紀錄', 'verbose_name_plural': '飛行任務紀錄'},
        ),
        migrations.RemoveField(
            model_name='missionrecord',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='missionrecord',
            name='mission_date',
        ),
        migrations.RemoveField(
            model_name='missionrecord',
            name='start_time',
        ),
        migrations.AddField(
            model_name='missionrecord',
            name='mission_end_date',
            field=models.DateField(default=datetime.date(2026, 2, 10), verbose_name='任務結束日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='missionrecord',
            name='mission_start_date',
            field=models.DateField(default=datetime.date(2026, 2, 10), verbose_name='任務開始日期'),
            preserve_default=False,
        ),
    ]
