# Generated by Django 5.2.10 on 2026-02-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneReservation', '0009_alter_missionrecord_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dronereservation',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='dronereviewer',
            name='can_manage_reviewers',
        ),
        migrations.RemoveField(
            model_name='dronereviewer',
            name='receive_email',
        ),
        migrations.DeleteModel(
            name='MissionRecord',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
