# Generated by Django 5.2.11 on 2026-02-12 02:21

import compareapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompareProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('plan_number', models.CharField(max_length=100)),
                ('budget_xml', models.FileField(blank=True, null=True, upload_to=compareapp.models.project_file_upload_to)),
                ('budget_original_name', models.CharField(blank=True, max_length=255)),
                ('budget_records', models.JSONField(blank=True, default=list)),
                ('budget_terms', models.JSONField(blank=True, default=list)),
                ('quantity_sheet', models.FileField(blank=True, null=True, upload_to=compareapp.models.project_file_upload_to)),
                ('quantity_original_name', models.CharField(blank=True, max_length=255)),
                ('quantity_records', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compare project',
                'verbose_name_plural': 'Compare projects',
                'ordering': ['-updated_at'],
            },
        ),
    ]
