# Generated by Django 5.2.11 on 2026-02-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('quantity_tolerance', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fuzzy_threshold', models.FloatField()),
                ('weighted_threshold', models.FloatField()),
                ('cross_encoder_threshold', models.FloatField(default=0.85)),
                ('cross_encoder_total_threshold', models.FloatField(blank=True, null=True)),
                ('sentence_model_name', models.CharField(default='paraphrase-multilingual-MiniLM-L12-v2', max_length=200)),
                ('cross_encoder_model_name', models.CharField(default='BAAI/bge-reranker-v2-m3', max_length=200)),
                ('baseline_meta', models.JSONField(blank=True, default=dict)),
                ('report_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_runs', to='compareapp.compareproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=64)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('left_source_id', models.CharField(blank=True, max_length=128)),
                ('right_source_id', models.CharField(blank=True, max_length=128)),
                ('left_name', models.CharField(blank=True, max_length=500)),
                ('right_name', models.CharField(blank=True, max_length=500)),
                ('score', models.FloatField(default=0.0)),
                ('name_score', models.FloatField(default=0.0)),
                ('unit_score', models.FloatField(default=0.0)),
                ('quantity_score', models.FloatField(default=0.0)),
                ('verdict', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('correct', 'Correct'), ('incorrect', 'Incorrect')], db_index=True, default='unreviewed', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='compareapp.comparisonrun')),
            ],
            options={
                'ordering': ['method', 'rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='comparisonrun',
            index=models.Index(fields=['project', 'created_at'], name='compareapp__project_ff31ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonrun',
            index=models.Index(fields=['project', 'status'], name='compareapp__project_2d3120_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonmatch',
            index=models.Index(fields=['run', 'method', 'rank'], name='compareapp__run_id_77ccfe_idx'),
        ),
        migrations.AddIndex(
            model_name='comparisonmatch',
            index=models.Index(fields=['run', 'verdict'], name='compareapp__run_id_189f03_idx'),
        ),
    ]
