# Generated by Django 5.2.11 on 2026-02-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0002_comparisonrun_comparisonmatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=120)),
                ('normalized_term', models.CharField(db_index=True, max_length=120, unique=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('budget', 'Budget Upload'), ('quantity', 'Quantity Upload'), ('match', 'Match Feedback')], default='manual', max_length=16)),
                ('selected_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-selected_count', 'term'],
                'indexes': [models.Index(fields=['is_active', 'selected_count'], name='compareapp__is_acti_3d8701_idx')],
            },
        ),
    ]
