# Generated by Django 5.2.11 on 2026-02-13 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compareapp', '0003_globalkeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compareproject',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_compare_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('manager', 'Manager')], db_index=True, default='viewer', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='compareapp.compareproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_project_access_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project_id', 'role', 'user_id'],
                'indexes': [models.Index(fields=['project', 'role'], name='compareapp__project_e0cb55_idx'), models.Index(fields=['user', 'role'], name='compareapp__user_id_77ac4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='compare_project_access_unique_project_user')],
            },
        ),
    ]
