# Generated by Django 5.2.11 on 2026-02-13

from django.conf import settings
from django.db import migrations


def assign_legacy_project_owner(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    user_model = apps.get_model(app_label, model_name)
    project_model = apps.get_model('compareapp', 'CompareProject')

    owner = (
        user_model.objects.filter(is_superuser=True).order_by('id').first()
        or user_model.objects.order_by('id').first()
    )
    if owner is None:
        return

    project_model.objects.filter(owner__isnull=True).update(owner=owner)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):
    dependencies = [
        ('compareapp', '0004_compareproject_owner_projectaccess'),
    ]

    operations = [
        migrations.RunPython(assign_legacy_project_owner, noop_reverse),
    ]
