# Generated by Django 5.2.11 on 2026-02-05 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品項名稱')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='價格')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('is_available', models.BooleanField(default=True, verbose_name='供應中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '菜單項目',
                'verbose_name_plural': '菜單項目',
                'ordering': ['restaurant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='營業中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '便當店',
                'verbose_name_plural': '便當店',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LunchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text='訂購時的員工姓名', max_length=100, verbose_name='員工全名')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('order_date', models.DateField(verbose_name='訂購日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_orders', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='LunchOrder.menuitem', verbose_name='訂購品項')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='LunchOrder.restaurant', verbose_name='便當店'),
        ),
    ]
