# Generated by Django 5.2.11 on 2026-02-11 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchOrder', '0002_alter_lunchorder_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='LunchOrder.restaurant', verbose_name='便當店')),
            ],
            options={
                'verbose_name': '便當店排程',
                'verbose_name_plural': '便當店排程',
                'ordering': ['-date'],
            },
        ),
    ]
