# Generated by Django 5.2.11 on 2026-02-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchOrder', '0003_restaurantschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_file',
            field=models.CharField(blank=True, help_text='例如: menu_dianguo.jpg, 檔案需放在 static/LunchOrder/ 下', max_length=100, null=True, verbose_name='菜單圖片檔名'),
        ),
    ]
