# Generated by Django 5.2.11 on 2026-03-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchOrder', '0005_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantschedule',
            name='order_cutoff_time',
            field=models.TimeField(blank=True, help_text='若未設定則使用系統預設 10:15', null=True, verbose_name='自訂截止時間'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('chicken', '雞肉餐盒'), ('duck', '鴨肉料理'), ('pork', '豬肉餐盒'), ('beef', '牛肉餐盒'), ('fish', '鮮魚餐盒'), ('noodle', '麵食/粥品'), ('soup', '精選湯品'), ('veg', '蔬食餐盒'), ('side', '美味小菜'), ('single', '單點品項'), ('drink', '冷泡茶飲'), ('other', '其他')], default='single', max_length=20, verbose_name='分類'),
        ),
    ]
