# Generated by Django 5.2.11 on 2026-03-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchOrder', '0006_restaurantschedule_order_cutoff_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_file',
            field=models.ImageField(blank=True, help_text='請上傳菜單圖片', null=True, upload_to='lunch_menus/', verbose_name='菜單圖片'),
        ),
    ]
