# Generated by Django 5.2.9 on 2026-01-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='縣市名稱')),
                ('latitude', models.FloatField(verbose_name='中心點緯度')),
                ('longitude', models.FloatField(verbose_name='中心點經度')),
            ],
            options={
                'verbose_name': '縣市',
                'verbose_name_plural': '縣市',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='鄉鎮區名稱')),
                ('latitude', models.FloatField(verbose_name='中心點緯度')),
                ('longitude', models.FloatField(verbose_name='中心點經度')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='townships', to='GeoCoding.county', verbose_name='所屬縣市')),
            ],
            options={
                'verbose_name': '鄉鎮區',
                'verbose_name_plural': '鄉鎮區',
                'ordering': ['county', 'name'],
                'unique_together': {('county', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='村里名稱')),
                ('latitude', models.FloatField(verbose_name='中心點緯度')),
                ('longitude', models.FloatField(verbose_name='中心點經度')),
                ('township', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='GeoCoding.township', verbose_name='所屬鄉鎮區')),
            ],
            options={
                'verbose_name': '村里',
                'verbose_name_plural': '村里',
                'ordering': ['township', 'name'],
                'unique_together': {('township', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GeoQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500, verbose_name='查詢字串')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='回傳緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='回傳經度')),
                ('confidence', models.FloatField(default=0.0, verbose_name='匹配信心度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查詢時間')),
                ('matched_county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='GeoCoding.county', verbose_name='匹配縣市')),
                ('matched_township', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='GeoCoding.township', verbose_name='匹配鄉鎮區')),
                ('matched_village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queries', to='GeoCoding.village', verbose_name='匹配村里')),
            ],
            options={
                'verbose_name': '查詢紀錄',
                'verbose_name_plural': '查詢紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
