# Generated by Django 5.2.9 on 2026-01-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoCoding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地標名稱')),
                ('aliases', models.CharField(blank=True, max_length=500, verbose_name='別名（逗號分隔）')),
                ('category', models.CharField(choices=[('mountain', '山岳'), ('lake', '湖泊'), ('park', '公園'), ('scenic', '風景區'), ('temple', '寺廟'), ('station', '車站'), ('airport', '機場'), ('port', '港口'), ('university', '大學'), ('hospital', '醫院'), ('museum', '博物館'), ('shopping', '商圈'), ('night_market', '夜市'), ('beach', '海灘'), ('hot_spring', '溫泉'), ('other', '其他')], default='other', max_length=20, verbose_name='類別')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='經度')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='GeoCoding.county', verbose_name='所屬縣市')),
                ('township', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmarks', to='GeoCoding.township', verbose_name='所屬鄉鎮區')),
            ],
            options={
                'verbose_name': '地標',
                'verbose_name_plural': '地標',
                'ordering': ['county', 'category', 'name'],
            },
        ),
    ]
