# Generated by Django 5.2.11 on 2026-02-05 03:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='群組名稱')),
                ('description', models.TextField(blank=True, verbose_name='群組說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_groups', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '記帳群組',
                'verbose_name_plural': '記帳群組',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成員名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='FriendExpense.expensegroup', verbose_name='所屬群組')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_memberships', to=settings.AUTH_USER_MODEL, verbose_name='關聯使用者')),
            ],
            options={
                'verbose_name': '群組成員',
                'verbose_name_plural': '群組成員',
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='品項說明')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='消費時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='FriendExpense.expensegroup', verbose_name='所屬群組')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expenses', to='FriendExpense.member', verbose_name='付款人')),
            ],
            options={
                'verbose_name': '消費記錄',
                'verbose_name_plural': '消費記錄',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='分攤金額')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='FriendExpense.expense', verbose_name='關聯消費')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_splits', to='FriendExpense.member', verbose_name='分攤成員')),
            ],
            options={
                'verbose_name': '分帳記錄',
                'verbose_name_plural': '分帳記錄',
                'unique_together': {('expense', 'member')},
            },
        ),
    ]
