# Generated by Django 5.2.11 on 2026-02-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendExpense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='expenses/%Y/%m/', verbose_name='收據/照片'),
        ),
    ]
