# Generated by Django 5.2.11 on 2026-02-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendExpense', '0002_expense_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分類名稱')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='FriendExpense.expensegroup', verbose_name='所屬群組')),
            ],
            options={
                'verbose_name': '消費分類',
                'verbose_name_plural': '消費分類',
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='FriendExpense.expensecategory', verbose_name='分類'),
        ),
    ]
