# Generated by Django 5.2.11 on 2026-02-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FriendExpense', '0003_expensecategory_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品項名稱')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金額')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='FriendExpense.expense', verbose_name='關聯消費')),
            ],
            options={
                'verbose_name': '消費細項',
                'verbose_name_plural': '消費細項',
            },
        ),
    ]
