# Generated by Django 5.2.12 on 2026-03-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Case', max_length=255, verbose_name='案件編號')),
                ('base_area', models.FloatField(verbose_name='基地面積')),
                ('original_volume', models.FloatField(verbose_name='建物原容積')),
                ('zone_type', models.CharField(max_length=50, verbose_name='使用分區')),
                ('volume_ratio', models.FloatField(verbose_name='容積率')),
                ('reward_parameters', models.JSONField(blank=True, default=dict, verbose_name='獎勵參數設定')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '專案容積計算',
                'verbose_name_plural': '專案容積計算',
            },
        ),
    ]
