# Generated by Django 5.2.12 on 2026-03-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, verbose_name='專案名稱')),
                ('base_area', models.FloatField(default=0.0, verbose_name='基地面積 (㎡)')),
                ('original_volume', models.FloatField(default=0.0, verbose_name='建物原容積 (㎡)')),
                ('land_use_zone', models.CharField(blank=True, max_length=100, verbose_name='使用分區')),
                ('floor_area_ratio', models.FloatField(default=0.0, verbose_name='容積率 (%)')),
                ('reward_items', models.JSONField(blank=True, default=list, verbose_name='獎勵項目明細')),
                ('total_reward_volume', models.FloatField(default=0.0, verbose_name='總獎勵容積')),
                ('final_volume', models.FloatField(default=0.0, verbose_name='總容積 (含獎勵)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '容積計算紀錄列表',
            },
        ),
    ]
