# Generated by Django 5.2.9 on 2026-01-05 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='報告標題')),
                ('html_file', models.FileField(upload_to='clash_reports/html/%Y/%m/%d/', verbose_name='HTML 檔案')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='clash_reports/csv/%Y/%m/%d/', verbose_name='CSV 檔案')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_reports', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '碰撞報告',
                'verbose_name_plural': '碰撞報告',
                'db_table': 'clash_report',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(verbose_name='資料行索引')),
                ('distance', models.FloatField(verbose_name='碰撞距離')),
                ('item1_id', models.CharField(max_length=50, verbose_name='項目1 ID')),
                ('item1_system', models.CharField(blank=True, max_length=10, verbose_name='項目1 系統')),
                ('item1_type', models.CharField(max_length=255, verbose_name='項目1 類型')),
                ('item1_count', models.IntegerField(verbose_name='項目1 出現次數')),
                ('item2_id', models.CharField(max_length=50, verbose_name='項目2 ID')),
                ('item2_system', models.CharField(blank=True, max_length=10, verbose_name='項目2 系統')),
                ('item2_type', models.CharField(max_length=255, verbose_name='項目2 類型')),
                ('item2_count', models.IntegerField(verbose_name='項目2 出現次數')),
                ('status', models.IntegerField(choices=[(0, '已解決'), (1, '作用中'), (2, '新')], default=1, verbose_name='狀態')),
                ('predicted_class', models.IntegerField(choices=[(0, '不是碰撞'), (1, '是碰撞')], verbose_name='預測分類')),
                ('confidence', models.FloatField(verbose_name='信心度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='ClashClassifier.clashreport', verbose_name='所屬報告')),
            ],
            options={
                'verbose_name': '分類結果',
                'verbose_name_plural': '分類結果',
                'db_table': 'classification_result',
                'ordering': ['report', 'row_index'],
                'indexes': [models.Index(fields=['report', 'row_index'], name='classificat_report__7b1da1_idx'), models.Index(fields=['predicted_class'], name='classificat_predict_432c3f_idx')],
            },
        ),
    ]
