# Generated by Django 5.2.9 on 2026-01-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClashClassifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('xgboost', 'XGBoost 模型'), ('pca', 'PCA 模型'), ('embedding_map', 'Embedding Map')], max_length=20, verbose_name='模型類型')),
                ('file', models.FileField(upload_to='ml_models/', verbose_name='模型檔案')),
                ('is_active', models.BooleanField(default=False, verbose_name='啟用中')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '機器學習模型',
                'verbose_name_plural': '機器學習模型',
                'db_table': 'ml_model',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='ml_model_model_t_daa8d6_idx')],
            },
        ),
    ]
