# Generated by Django 5.2.9 on 2026-01-08 06:46

import SinoFile.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClashClassifier', '0002_mlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clashreport',
            name='csv_file',
            field=SinoFile.fields.SinoFileField(blank=True, null=True, upload_to='clash_reports/csv/%Y/%m/%d/', verbose_name='CSV 檔案'),
        ),
        migrations.AlterField(
            model_name='clashreport',
            name='html_file',
            field=SinoFile.fields.SinoFileField(upload_to='clash_reports/html/%Y/%m/%d/', verbose_name='HTML 檔案'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='file',
            field=SinoFile.fields.SinoFileField(upload_to='ml_models/', verbose_name='模型檔案'),
        ),
    ]
