# Generated by Django 5.2.9 on 2026-01-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClashClassifier', '0002_mlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('xgboost', 'XGBoost 模型'), ('pca', 'PCA 模型'), ('embedding_map', 'Embedding Map'), ('sentence_transformer', 'SentenceTransformer 模型')], max_length=20, verbose_name='模型類型'),
        ),
    ]
