# Generated by Django 5.2.9 on 2026-01-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClashClassifier', '0003_alter_mlmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='extracted_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='解壓縮路徑'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='file',
            field=models.FileField(help_text='sentence_transformer 請上傳 ZIP 檔', upload_to='ml_models/', verbose_name='模型檔案'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('xgboost', 'XGBoost 模型'), ('pca', 'PCA 模型'), ('embedding_map', 'Embedding Map'), ('sentence_transformer', 'SentenceTransformer 模型 (ZIP)')], max_length=20, verbose_name='模型類型'),
        ),
    ]
