
# Generated by Django 5.2.9 on 2026-01-22 05:30
from django.db import migrations, models
class Migration(migrations.Migration):

    dependencies = [
        ('ClashClassifier', '0005_use_sinofilefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='file',
            field=models.FileField(help_text='sentence_transformer 請上傳 ZIP 檔', upload_to='ml_models/', verbose_name='模型檔案'),
        ),
    ]
