# Generated by Django 5.2.8 on 2025-12-04 11:48

import django_ckeditor_5.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, verbose_name='分類說明')),
                ('order', models.IntegerField(default=0, help_text='數字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='成果名稱')),
                ('summary', models.CharField(max_length=200, verbose_name='簡介')),
                ('video', models.FileField(help_text='請上傳10分鐘以下的影片', upload_to='achievements/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])], verbose_name='展示影片')),
                ('url', models.URLField(blank=True, verbose_name='相關網址')),
                ('documentation', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='說明文件', config_name='extends')),
                ('view_count', models.IntegerField(default=0, verbose_name='瀏覽次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_achievements', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('developers', models.ManyToManyField(blank=True, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='協同開發者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='DevShowcase.category', verbose_name='分類')),
            ],
            options={
                'verbose_name': '開發成果',
                'verbose_name_plural': '開發成果',
                'ordering': ['-view_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='已解決')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言時間')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DevShowcase.achievement', verbose_name='成果')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='瀏覽時間')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='DevShowcase.achievement', verbose_name='成果')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '瀏覽記錄',
                'verbose_name_plural': '瀏覽記錄',
                'ordering': ['-viewed_at'],
                'unique_together': {('achievement', 'user')},
            },
        ),
    ]
