# Generated by Django 5.2.9 on 2026-01-08 06:46

import SinoFile.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DevShowcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='video',
            field=SinoFile.fields.SinoFileField(help_text='請上傳10分鐘以下的影片', upload_to='achievements/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'webm'])], verbose_name='展示影片'),
        ),
    ]
