# Generated by Django 5.2.9 on 2025-12-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '建立'), ('UPDATE', '更新'), ('DELETE', '刪除'), ('DOWNLOAD', '下載'), ('UPLOAD', '上傳')], max_length=20, verbose_name='操作類型')),
                ('model_name', models.CharField(max_length=100, verbose_name='資料模型名稱')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='物件ID')),
                ('detail', models.JSONField(default=dict, verbose_name='操作詳情')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='時間點')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '操作紀錄',
                'verbose_name_plural': '操作紀錄',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分組名稱')),
                ('code', models.CharField(max_length=50, verbose_name='分組代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
            ],
            options={
                'verbose_name': '專業分組',
                'verbose_name_plural': '專業分組',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='標案名稱')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='標案編號')),
                ('description', models.TextField(blank=True, verbose_name='標案說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('status', models.CharField(choices=[('PREPARING', '籌備中'), ('ONGOING', '進行中'), ('FINISHED', '已結案')], default='PREPARING', max_length=20, verbose_name='標案狀態')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '標案',
                'verbose_name_plural': '標案',
            },
        ),
        migrations.CreateModel(
            name='PriceInquiryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('version', models.IntegerField(default=1, verbose_name='版本號')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('description', models.TextField(blank=True, verbose_name='版本說明')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否為最新版本')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.discipline', verbose_name='專業分組')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.project', verbose_name='標案')),
            ],
            options={
                'verbose_name': '訪價資料',
                'verbose_name_plural': '訪價資料',
            },
        ),
        migrations.CreateModel(
            name='PriceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, verbose_name='項目代碼')),
                ('item_name', models.CharField(max_length=255, verbose_name='項目名稱')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='原始單價')),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='調整後單價')),
                ('reason', models.TextField(verbose_name='調整原因')),
                ('adjusted_at', models.DateTimeField(auto_now_add=True, verbose_name='調整時間')),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='調整者')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.discipline', verbose_name='專業分組')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_adjustments', to='BudgetReview.project', verbose_name='標案')),
            ],
            options={
                'verbose_name': '單價調整紀錄',
                'verbose_name_plural': '單價調整紀錄',
            },
        ),
        migrations.CreateModel(
            name='FinalBudgetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('version', models.IntegerField(default=1, verbose_name='版本號')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('description', models.TextField(blank=True, verbose_name='版本說明')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否為最新版本')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='是否為保密版')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.discipline', verbose_name='專業分組')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.project', verbose_name='標案')),
            ],
            options={
                'verbose_name': '整合版預算',
                'verbose_name_plural': '整合版預算',
            },
        ),
        migrations.AddField(
            model_name='discipline',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='BudgetReview.project', verbose_name='標案'),
        ),
        migrations.CreateModel(
            name='BudgetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('version', models.IntegerField(default=1, verbose_name='版本號')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('description', models.TextField(blank=True, verbose_name='版本說明')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否為最新版本')),
                ('budget_type', models.CharField(choices=[('GROUP', '分組預算'), ('EXTERNAL', '外部門預算')], default='GROUP', max_length=20, verbose_name='預算類型')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.discipline', verbose_name='專業分組')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.project', verbose_name='標案')),
            ],
            options={
                'verbose_name': '分組預算',
                'verbose_name_plural': '分組預算',
            },
        ),
        migrations.CreateModel(
            name='QuantityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('version', models.IntegerField(default=1, verbose_name='版本號')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('description', models.TextField(blank=True, verbose_name='版本說明')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否為最新版本')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.discipline', verbose_name='專業分組')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.project', verbose_name='標案')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '數量計算書',
                'verbose_name_plural': '數量計算書',
            },
        ),
        migrations.AlterUniqueTogether(
            name='discipline',
            unique_together={('project', 'code')},
        ),
    ]
