# Generated by Django 5.2.9 on 2025-12-19 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetReview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='discipline_memberships', to=settings.AUTH_USER_MODEL, verbose_name='組員'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='負責人'),
        ),
    ]
