# Generated by Django 5.2.9 on 2025-12-20 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetReview', '0003_project_responsible_user_alter_project_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='budget_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_budgets', to=settings.AUTH_USER_MODEL, verbose_name='預算管理員'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='budget_members',
            field=models.ManyToManyField(blank=True, related_name='budget_memberships', to=settings.AUTH_USER_MODEL, verbose_name='預算成員'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='discipline_members', to=settings.AUTH_USER_MODEL, verbose_name='專業成員'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_disciplines', to=settings.AUTH_USER_MODEL, verbose_name='專業管理員'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL, verbose_name='標案管理員'),
        ),
    ]
