# Generated by Django 5.2.9 on 2025-12-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetReview', '0004_discipline_budget_manager_discipline_budget_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['project', 'code'], 'verbose_name': '專業分組', 'verbose_name_plural': '專業分組'},
        ),
        migrations.AddField(
            model_name='discipline',
            name='is_overall',
            field=models.BooleanField(default=False, verbose_name='是否為整合專業'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(default='01', max_length=10, verbose_name='專業代碼'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=100, verbose_name='專業名稱'),
        ),
    ]
