# Generated by Django 5.1.1 on 2025-12-20 09:00

from django.db import migrations


def populate_codes_and_create_overall(apps, schema_editor):
    """
    為現有的 Discipline 分配代碼，並為每個 Project 創建整合專業
    """
    Project = apps.get_model('BudgetReview', 'Project')
    Discipline = apps.get_model('BudgetReview', 'Discipline')
    
    for project in Project.objects.all():
        # 為現有專業分配代碼（從 01 開始）
        existing_disciplines = Discipline.objects.filter(project=project).order_by('id')
        for idx, disc in enumerate(existing_disciplines, start=1):
            disc.code = f'{idx:02d}'
            disc.is_overall = False
            disc.save()
        
        # 創建整合專業（代碼 00）
        Discipline.objects.create(
            project=project,
            code='00',
            name='整合專業',
            is_overall=True,
            responsible_user=project.responsible_user
        )


def reverse_populate(apps, schema_editor):
    """
    回滾時刪除整合專業
    """
    Discipline = apps.get_model('BudgetReview', 'Discipline')
    Discipline.objects.filter(is_overall=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetReview', '0005_alter_discipline_options_discipline_is_overall_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_codes_and_create_overall, reverse_populate),
    ]
