# Generated by Django 5.2.9 on 2025-12-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetReview', '0006_populate_discipline_codes_and_create_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalbudgetfile',
            name='file_type',
            field=models.CharField(choices=[('INTEGRATED', '整合預算'), ('BLANK_TENDER', '空白標單')], default='INTEGRATED', max_length=20, verbose_name='檔案類型'),
        ),
    ]
