# Generated by Django 5.2.9 on 2025-12-21 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetReview', '0007_finalbudgetfile_file_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='responsible_user',
        ),
        migrations.AddField(
            model_name='budgetfile',
            name='is_submitted',
            field=models.BooleanField(default=True, verbose_name='是否已提送'),
        ),
        migrations.AddField(
            model_name='budgetfile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提送時間'),
        ),
        migrations.AddField(
            model_name='budgetfile',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)s_files', to=settings.AUTH_USER_MODEL, verbose_name='提送者'),
        ),
        migrations.AddField(
            model_name='finalbudgetfile',
            name='is_submitted',
            field=models.BooleanField(default=True, verbose_name='是否已提送'),
        ),
        migrations.AddField(
            model_name='finalbudgetfile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提送時間'),
        ),
        migrations.AddField(
            model_name='finalbudgetfile',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)s_files', to=settings.AUTH_USER_MODEL, verbose_name='提送者'),
        ),
        migrations.AddField(
            model_name='priceinquiryfile',
            name='is_submitted',
            field=models.BooleanField(default=True, verbose_name='是否已提送'),
        ),
        migrations.AddField(
            model_name='priceinquiryfile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提送時間'),
        ),
        migrations.AddField(
            model_name='priceinquiryfile',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)s_files', to=settings.AUTH_USER_MODEL, verbose_name='提送者'),
        ),
        migrations.AddField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='標案管理員'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='刪除時間'),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_projects', to=settings.AUTH_USER_MODEL, verbose_name='刪除者'),
        ),
        migrations.AddField(
            model_name='quantityfile',
            name='is_submitted',
            field=models.BooleanField(default=True, verbose_name='是否已提送'),
        ),
        migrations.AddField(
            model_name='quantityfile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提送時間'),
        ),
        migrations.AddField(
            model_name='quantityfile',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_%(class)s_files', to=settings.AUTH_USER_MODEL, verbose_name='提送者'),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='階段名稱')),
                ('order', models.IntegerField(verbose_name='階段順序')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='檔案提送截止時間')),
                ('description', models.TextField(blank=True, verbose_name='階段說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='BudgetReview.project', verbose_name='標案')),
            ],
            options={
                'verbose_name': '標案階段',
                'verbose_name_plural': '標案階段',
                'ordering': ['project', 'order'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.AddField(
            model_name='budgetfile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.stage', verbose_name='標案階段'),
        ),
        migrations.AddField(
            model_name='finalbudgetfile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.stage', verbose_name='標案階段'),
        ),
        migrations.AddField(
            model_name='priceinquiryfile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.stage', verbose_name='標案階段'),
        ),
        migrations.AddField(
            model_name='quantityfile',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetReview.stage', verbose_name='標案階段'),
        ),
    ]
