# Generated by Django 5.2.9 on 2026-01-08 06:46

import SinoFile.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetReview', '0008_remove_project_responsible_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetfile',
            name='file',
            field=SinoFile.fields.SinoFileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案'),
        ),
        migrations.AlterField(
            model_name='finalbudgetfile',
            name='file',
            field=SinoFile.fields.SinoFileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案'),
        ),
        migrations.AlterField(
            model_name='priceinquiryfile',
            name='file',
            field=SinoFile.fields.SinoFileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案'),
        ),
        migrations.AlterField(
            model_name='quantityfile',
            name='file',
            field=SinoFile.fields.SinoFileField(upload_to='budget_review/%Y/%m/%d/', verbose_name='檔案'),
        ),
    ]
