# Generated by Django 5.2.10 on 2026-02-03 03:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('code', models.CharField(choices=[('TW_FINANCE', '台灣財經'), ('US_FINANCE', '美國財經'), ('INDUSTRY', '產業動態'), ('GLOBAL', '國際經濟')], max_length=20, unique=True, verbose_name='分類代碼')),
                ('description', models.TextField(blank=True, verbose_name='分類說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '新聞分類',
                'verbose_name_plural': '新聞分類',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='股市名稱')),
                ('code', models.CharField(choices=[('TWSE', '台北股市'), ('NYSE', '紐約證券交易所'), ('NASDAQ', '那斯達克')], max_length=20, unique=True, verbose_name='股市代碼')),
                ('country', models.CharField(max_length=50, verbose_name='國家/地區')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
            ],
            options={
                'verbose_name': '股市類型',
                'verbose_name_plural': '股市類型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='標題')),
                ('content', models.TextField(blank=True, verbose_name='內容')),
                ('source', models.CharField(max_length=255, verbose_name='來源')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='來源網址')),
                ('published_at', models.DateTimeField(verbose_name='發布時間')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='FinanceInsight.newscategory', verbose_name='分類')),
            ],
            options={
                'verbose_name': '財經新聞',
                'verbose_name_plural': '財經新聞',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='個股編號')),
                ('stock_name', models.CharField(max_length=100, verbose_name='股票名稱')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='盤價')),
                ('price_change', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='漲跌')),
                ('price_change_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='漲跌幅(%)')),
                ('recommendation_date', models.DateField(default=django.utils.timezone.now, verbose_name='建議日期')),
                ('recommendation_reason', models.TextField(blank=True, verbose_name='推薦原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='FinanceInsight.stockmarket', verbose_name='股市')),
            ],
            options={
                'verbose_name': '選股建議',
                'verbose_name_plural': '選股建議',
                'ordering': ['-recommendation_date', 'stock_code'],
            },
        ),
        migrations.CreateModel(
            name='StockTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_description', models.TextField(verbose_name='趨勢說明')),
                ('analysis_date', models.DateField(default=django.utils.timezone.now, verbose_name='分析日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='FinanceInsight.stockrecommendation', verbose_name='關聯股票')),
            ],
            options={
                'verbose_name': '個股趨勢',
                'verbose_name_plural': '個股趨勢',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyNewsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('summary', models.TextField(verbose_name='當日新聞摘要')),
                ('conclusion', models.TextField(verbose_name='當日新聞總結')),
                ('news_count', models.IntegerField(default=0, verbose_name='新聞數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='FinanceInsight.newscategory', verbose_name='新聞分類')),
            ],
            options={
                'verbose_name': '當日新聞摘要',
                'verbose_name_plural': '當日新聞摘要',
                'ordering': ['-date'],
                'unique_together': {('category', 'date')},
            },
        ),
    ]
