# Generated by Django 5.2.12 on 2026-03-26 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('instant', '單一時刻陰影'), ('hours', '曝曬時數'), ('solar', '日射量分析')], max_length=20, verbose_name='分析類型')),
                ('parameters', models.JSONField(default=dict, verbose_name='分析參數 (JSON)')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('success', '成功'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='執行狀態')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
            ],
            options={
                'verbose_name': '分析任務',
                'verbose_name_plural': '分析任務',
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_type', models.CharField(choices=[('raster', '柵格 (Heatmap)'), ('mesh', '網格 (Mesh)'), ('csv', '數據報表'), ('image', '截圖/影像')], max_length=20, verbose_name='結果類型')),
                ('data_file', models.FileField(upload_to='lumasite/results/%Y/%m/%d/', verbose_name='結果檔案')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='統計摘要 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='LumaSite.analysisrun', verbose_name='關聯任務')),
            ],
            options={
                'verbose_name': '分析結果',
                'verbose_name_plural': '分析結果',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='專案名稱')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='地址/地點描述')),
                ('center_lat', models.FloatField(verbose_name='中心緯度')),
                ('center_lng', models.FloatField(verbose_name='中心經度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lumasite_projects', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '專案',
                'verbose_name_plural': '專案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='方案名稱')),
                ('description', models.TextField(blank=True, verbose_name='方案描述')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否為當前方案')),
                ('version_no', models.IntegerField(default=1, verbose_name='版本號')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='LumaSite.project', verbose_name='關聯專案')),
            ],
            options={
                'verbose_name': '分析方案',
                'verbose_name_plural': '分析方案',
            },
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='LumaSite.scenario', verbose_name='關聯方案'),
        ),
        migrations.CreateModel(
            name='SceneAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('terrain', '地形'), ('context', '周邊建物'), ('design', '設計量體'), ('tree', '植栽')], max_length=20, verbose_name='資產類型')),
                ('source_type', models.CharField(choices=[('osm', 'OpenStreetMap'), ('upload', '使用者上傳'), ('generated', '系統生成')], max_length=20, verbose_name='來源類型')),
                ('file', models.FileField(upload_to='lumasite/assets/%Y/%m/%d/', verbose_name='資產檔案')),
                ('transform_json', models.JSONField(blank=True, default=dict, verbose_name='轉換矩陣 (JSON)')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元數據 (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='LumaSite.scenario', verbose_name='關聯方案')),
            ],
            options={
                'verbose_name': '場景資產',
                'verbose_name_plural': '場景資產',
            },
        ),
    ]
