# Generated by Django 5.2.8 on 2025-12-05 09:18

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RndRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='請簡潔描述需求主題', max_length=200, verbose_name='需求主題')),
                ('demand_quantity', models.TextField(help_text='請說明每周使用幾小時、需求人數等資訊', verbose_name='需求量')),
                ('data_source', models.TextField(help_text='請說明輸入的資料是什麼、來自於哪裡', verbose_name='資料來源')),
                ('processing_flow', django_ckeditor_5.fields.CKEditor5Field(help_text='請提供完整的使用流程說明', verbose_name='處理流程')),
                ('expected_outcome', models.TextField(blank=True, help_text='若實作此需求會帶來什麼好處', verbose_name='預期效益')),
                ('priority_level', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='緊迫程度')),
                ('status', models.CharField(choices=[('pending', '提案中'), ('reviewing', '審核中'), ('accepted', '已採納'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnd_requests', to=settings.AUTH_USER_MODEL, verbose_name='提案人')),
            ],
            options={
                'verbose_name': '研發需求',
                'verbose_name_plural': '研發需求',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RndRequestVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.SmallIntegerField(choices=[(1, '贊成'), (-1, '反對')], verbose_name='投票類型')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='投票時間')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='RndRequest.rndrequest', verbose_name='需求')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnd_votes', to=settings.AUTH_USER_MODEL, verbose_name='投票者')),
            ],
            options={
                'verbose_name': '投票記錄',
                'verbose_name_plural': '投票記錄',
                'ordering': ['-voted_at'],
                'unique_together': {('request', 'user')},
            },
        ),
    ]
