# Generated by Django 5.2.8 on 2025-12-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RndRequest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RndRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='請輸入您的意見或建議', verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言時間')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='RndRequest.rndrequest', verbose_name='需求')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnd_comments', to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '留言記錄',
                'verbose_name_plural': '留言記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
