# Generated by Django 5.2.8 on 2025-12-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RndRequest', '0002_rndrequestcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rndrequest',
            options={'ordering': ['-created_at'], 'verbose_name': '願望', 'verbose_name_plural': '願望'},
        ),
        migrations.AlterField(
            model_name='rndrequest',
            name='data_source',
            field=models.TextField(help_text='請說明目前狀況是什麼、問題來自於哪裡', verbose_name='現況說明'),
        ),
        migrations.AlterField(
            model_name='rndrequest',
            name='demand_quantity',
            field=models.TextField(help_text='請說明每周使用幾小時、影響人數等資訊', verbose_name='使用量/影響範圍'),
        ),
        migrations.AlterField(
            model_name='rndrequest',
            name='title',
            field=models.CharField(help_text='請簡潔描述您的願望主題', max_length=200, verbose_name='願望主題'),
        ),
    ]
