# Generated by Django 5.2.9 on 2026-01-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='專案名稱')),
                ('description', models.TextField(blank=True, verbose_name='專案描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='site360/projects/', verbose_name='封面圖片')),
            ],
            options={
                'verbose_name': '專案',
                'verbose_name_plural': '專案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='場景標題')),
                ('image', models.ImageField(upload_to='site360/scenes/', verbose_name='360全景圖')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('pitch', models.FloatField(default=0, help_text='Starting pitch in degrees', verbose_name='初始俯仰角 (Pitch)')),
                ('yaw', models.FloatField(default=0, help_text='Starting yaw in degrees', verbose_name='初始偏航角 (Yaw)')),
                ('hfov', models.FloatField(default=110, help_text='Horizontal field of view in degrees', verbose_name='視場角 (HFOV)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='site360.project', verbose_name='所屬專案')),
            ],
            options={
                'verbose_name': '場景',
                'verbose_name_plural': '場景',
                'ordering': ['order', 'title'],
            },
        ),
    ]
