# Generated by Django 5.2.9 on 2026-01-09 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_type', models.CharField(choices=[('text', '文字公告 (Text)'), ('image', '照片 (Image)'), ('video', '影片 (Video)')], default='text', max_length=10, verbose_name='類型')),
                ('pitch', models.FloatField(verbose_name='俯仰角 (Pitch)')),
                ('yaw', models.FloatField(verbose_name='偏航角 (Yaw)')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='詳細說明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site360/hotspots/images/', verbose_name='圖片內容')),
                ('video', models.FileField(blank=True, null=True, upload_to='site360/hotspots/videos/', verbose_name='影片內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='site360.scene', verbose_name='所屬場景')),
            ],
            options={
                'verbose_name': '熱點內容',
                'verbose_name_plural': '熱點內容',
            },
        ),
    ]
