# Generated by Django 5.2.9 on 2026-01-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0002_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='icon',
            field=models.CharField(default='fas fa-info-circle', max_length=50, verbose_name='圖示'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='hotspot_type',
            field=models.CharField(choices=[('text', '文字公告 (Text)'), ('text_hover', '懸浮文字 (Hover Text)'), ('image', '照片 (Image)'), ('video', '影片 (Video)')], default='text', max_length=10, verbose_name='類型'),
        ),
    ]
