# Generated by Django 5.2.9 on 2026-01-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0003_hotspot_icon_alter_hotspot_hotspot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='hotspot_type',
            field=models.CharField(choices=[('text', '文字公告 (Text)'), ('text_hover', '懸浮文字 (Hover Text)'), ('image', '照片 (Image)'), ('image_hover', '懸浮照片 (Hover Image)'), ('video', '影片 (Video)')], default='text', max_length=20, verbose_name='類型'),
        ),
    ]
