# Generated by Django 5.2.9 on 2026-01-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0004_alter_hotspot_hotspot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='icon_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='圖示顏色'),
        ),
    ]
