# Generated by Django 5.2.9 on 2026-01-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0006_alter_hotspot_hotspot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='hotspot_type',
            field=models.CharField(choices=[('text', '文字'), ('text_hover', '懸浮文字'), ('image', '圖片'), ('image_hover', '懸浮圖片'), ('video', '影片'), ('video_hover', '懸浮影片')], default='text', max_length=20, verbose_name='類型'),
        ),
    ]
