# Generated by Django 5.2.9 on 2026-01-12 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0007_alter_hotspot_hotspot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='source_hotspot',
            field=models.ForeignKey(blank=True, help_text='The original hotspot this was imported from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_by', to='site360.hotspot'),
        ),
    ]
