# Generated by Django 5.2.9 on 2026-01-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0008_hotspot_source_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
