# Generated by Django 5.2.9 on 2026-01-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0009_hotspot_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='next_pitch',
            field=models.FloatField(default=-5, verbose_name='下一張熱點 Pitch'),
        ),
        migrations.AddField(
            model_name='scene',
            name='next_yaw',
            field=models.FloatField(default=0, verbose_name='下一張熱點 Yaw'),
        ),
        migrations.AddField(
            model_name='scene',
            name='prev_pitch',
            field=models.FloatField(default=-5, verbose_name='上一張熱點 Pitch'),
        ),
        migrations.AddField(
            model_name='scene',
            name='prev_yaw',
            field=models.FloatField(default=180, verbose_name='上一張熱點 Yaw'),
        ),
    ]
