# Generated by Django 5.2.9 on 2026-01-14 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0010_scene_next_pitch_scene_next_yaw_scene_prev_pitch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='is_latest_version',
            field=models.BooleanField(default=True, help_text='Indicates if this is the latest version', verbose_name='是否為最新版本'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='original_resource',
            field=models.ForeignKey(blank=True, help_text='Points to the original resource in the version chain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='site360.hotspot'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='version_number',
            field=models.PositiveIntegerField(default=1, help_text='Version number of this resource', verbose_name='版本號'),
        ),
    ]
