# Generated by Django 5.2.9 on 2026-01-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0011_hotspot_is_latest_version_hotspot_original_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='詳細地址'),
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='縣市'),
        ),
        migrations.AddField(
            model_name='project',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='區域'),
        ),
    ]
