# Generated by Django 5.2.9 on 2026-01-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0012_project_address_detail_project_city_project_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='經度'),
        ),
    ]
