# Generated by Django 5.2.10 on 2026-01-16 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('site360', '0013_project_latitude_project_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', '建立'), ('UPDATE', '更新'), ('DELETE', '刪除'), ('VIEW', '查看'), ('LOGIN', '登入'), ('LOGOUT', '登出'), ('UPLOAD', '上傳'), ('DOWNLOAD', '下載'), ('REFERENCE', '引用'), ('REORDER', '重新排序'), ('MOVE', '移動'), ('SET_COVER', '設為封面'), ('OTHER', '其他')], db_index=True, max_length=20, verbose_name='操作類型')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='對象ID')),
                ('object_repr', models.CharField(blank=True, help_text='操作對象的字串表示', max_length=500, verbose_name='對象描述')),
                ('action_detail', models.JSONField(blank=True, default=dict, help_text='包含請求參數、變更內容等詳細資訊', verbose_name='操作詳情')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='客戶端IP地址', null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, help_text='瀏覽器和操作系統資訊', max_length=500, verbose_name='用戶代理')),
                ('request_path', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='請求路徑')),
                ('request_method', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE 等', max_length=10, verbose_name='請求方法')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='用於追蹤同一會話的操作', max_length=100, verbose_name='會話KEY')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作時間')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='對象類型')),
                ('user', models.ForeignKey(blank=True, help_text='執行操作的使用者，null 表示匿名用戶', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者操作記錄',
                'verbose_name_plural': '使用者操作記錄',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type'], name='site360_use_user_id_280e4c_idx'), models.Index(fields=['content_type', 'object_id'], name='site360_use_content_d10438_idx'), models.Index(fields=['created_at'], name='site360_use_created_cc4acc_idx'), models.Index(fields=['session_key'], name='site360_use_session_87227f_idx')],
            },
        ),
    ]
