# Generated by Django 5.2.10 on 2026-03-04 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0014_useractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspots', to='site360.scene', verbose_name='所屬場景'),
        ),
    ]
