# Generated by Django 5.2.10 on 2026-03-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0015_alter_hotspot_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(help_text='危害類型的項次編號', unique=True, verbose_name='項次')),
                ('name', models.CharField(max_length=200, verbose_name='危害類型名稱')),
                ('description', models.TextField(blank=True, verbose_name='危害類型說明')),
            ],
            options={
                'verbose_name': '危害類型',
                'verbose_name_plural': '危害類型',
                'ordering': ['serial_number'],
            },
        ),
    ]
