# Generated by Django 5.2.10 on 2026-03-04 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0016_hazardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='hazard_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspots', to='site360.hazardtype', verbose_name='危害類型'),
        ),
    ]
