# Generated by Django 5.2.10 on 2026-03-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0017_hotspot_hazard_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='next_icon',
            field=models.CharField(default='fas fa-arrow-right', max_length=50, verbose_name='下一張熱點圖示'),
        ),
        migrations.AddField(
            model_name='scene',
            name='prev_icon',
            field=models.CharField(default='fas fa-arrow-left', max_length=50, verbose_name='上一張熱點圖示'),
        ),
    ]
