# Generated by Django 5.2.10 on 2026-03-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0018_add_nav_icon_to_scene'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(help_text='Excel 中的項次編號', verbose_name='項次')),
                ('source_folder', models.CharField(blank=True, choices=[('台北勞檢', '台北勞檢'), ('桃園勞檢', '桃園勞檢'), ('職安署', '職安署'), ('其他', '其他')], max_length=50, verbose_name='資料夾名稱')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始檔案名稱')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site360/preset_hotspots/', verbose_name='圖片')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='詳細說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('hazard_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preset_hotspots', to='site360.hazardtype', verbose_name='危害類型')),
            ],
            options={
                'verbose_name': '預設熱點',
                'verbose_name_plural': '預設熱點',
                'ordering': ['serial_number'],
            },
        ),
    ]
