# Generated by Django 5.2.10 on 2026-03-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0019_add_preset_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='preset_source',
            field=models.ForeignKey(blank=True, help_text='若此熱點是從預設資料庫匯入，記錄對應的 PresetHotspot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_hotspots', to='site360.presethotspot', verbose_name='預設素材來源'),
        ),
    ]
