# Generated by Django 5.2.10 on 2026-03-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0020_add_preset_source_to_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='hazard_types',
            field=models.ManyToManyField(blank=True, help_text='可選擇多個危害類型', related_name='hotspots', to='site360.hazardtype', verbose_name='危害類型'),
        ),
        migrations.AddField(
            model_name='presethotspot',
            name='hazard_types',
            field=models.ManyToManyField(blank=True, help_text='可選擇多個危害類型', related_name='preset_hotspots', to='site360.hazardtype', verbose_name='危害類型'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='hazard_type',
            field=models.ForeignKey(blank=True, help_text='舊版單選欄位，將停用，請改用 hazard_types。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_hotspots', to='site360.hazardtype', verbose_name='危害類型(單選-舊版)'),
        ),
        migrations.AlterField(
            model_name='presethotspot',
            name='hazard_type',
            field=models.ForeignKey(blank=True, help_text='舊版單選欄位，將停用，請改用 hazard_types。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_preset_hotspots', to='site360.hazardtype', verbose_name='危害類型(單選-舊版)'),
        ),
    ]
