# Generated by Django 5.2.10 on 2026-03-06 09:24

from django.db import migrations


def forward_func(apps, schema_editor):
    Hotspot = apps.get_model('site360', 'Hotspot')
    for hotspot in Hotspot.objects.all():
        if hotspot.hazard_type:
            hotspot.hazard_types.add(hotspot.hazard_type)
            
    PresetHotspot = apps.get_model('site360', 'PresetHotspot')
    for preset in PresetHotspot.objects.all():
        if preset.hazard_type:
            preset.hazard_types.add(preset.hazard_type)

def reverse_func(apps, schema_editor):
    Hotspot = apps.get_model('site360', 'Hotspot')
    for hotspot in Hotspot.objects.all():
        first_hazard = hotspot.hazard_types.first()
        if first_hazard:
            hotspot.hazard_type = first_hazard
            hotspot.save(update_fields=['hazard_type'])
            
    PresetHotspot = apps.get_model('site360', 'PresetHotspot')
    for preset in PresetHotspot.objects.all():
        first_hazard = preset.hazard_types.first()
        if first_hazard:
            preset.hazard_type = first_hazard
            preset.save(update_fields=['hazard_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0021_hotspot_hazard_types_presethotspot_hazard_types_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
