# Generated by Django 5.2.12 on 2026-03-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0022_copy_hazard_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='external_form_uid',
            field=models.CharField(blank=True, db_index=True, default='', help_text='從外部平台（如 PMIS / CMS）匯入時，記錄來源表單的 UUID，供未來推薦或對應使用。', max_length=100, verbose_name='外部表單 UID'),
        ),
    ]
