# Generated by Django 5.2.12 on 2026-03-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0023_add_external_form_uid_to_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='外部平台的圖片 UUID', max_length=100, null=True, unique=True, verbose_name='外部 ID'),
        ),
    ]
