# Generated by Django 5.2.12 on 2026-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0024_scene_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='計畫編號'),
        ),
        migrations.AddField(
            model_name='project',
            name='tender_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='標別'),
        ),
        migrations.AddField(
            model_name='project',
            name='tender_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='名稱'),
        ),
    ]
