# Generated by Django 5.2.12 on 2026-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0025_project_project_code_project_tender_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tender_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='工程名稱'),
        ),
    ]
