# Generated by Django 5.2.12 on 2026-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0026_alter_project_tender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='表單建立日期'),
        ),
    ]
