# Generated by Django 5.2.12 on 2026-03-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0027_project_doc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='form_uid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='外部表單 UID'),
        ),
    ]
