# Generated by Django 5.2.12 on 2026-03-13 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0028_project_form_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='site360.project', verbose_name='所屬專案'),
        ),
    ]
