# Generated by Django 5.2.12 on 2026-03-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site360', '0029_hotspot_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='video_url',
            field=models.CharField(blank=True, help_text='支援 YouTube 或外部影片連結', max_length=500, null=True, verbose_name='影片網址'),
        ),
    ]
