# Generated by Django 5.2.8 on 2025-12-15 01:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='教材標題')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL標識符')),
                ('description', models.TextField(verbose_name='教材簡介')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tutorials/covers/%Y/%m/', verbose_name='封面圖片')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否發布')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='問題內容')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解決')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_questions', to=settings.AUTH_USER_MODEL, verbose_name='提問者')),
            ],
            options={
                'verbose_name': '提問',
                'verbose_name_plural': '提問',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答內容')),
                ('is_from_maintainer', models.BooleanField(default=False, help_text='是否為教材維護者的回答', verbose_name='維護者回答')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_answers', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='TutorialHub.question', verbose_name='問題')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='步驟標題')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序順序')),
                ('is_expanded_default', models.BooleanField(default=False, help_text='預設是否展開此步驟', verbose_name='預設展開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='TutorialHub.tutorial', verbose_name='教材')),
            ],
            options={
                'verbose_name': '教材步驟',
                'verbose_name_plural': '教材步驟',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet_type', models.CharField(choices=[('text', '文字'), ('image', '圖片'), ('code', '程式碼')], default='text', max_length=10, verbose_name='片段類型')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序順序')),
                ('content', models.TextField(blank=True, help_text='文字或程式碼內容', null=True, verbose_name='內容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutorials/images/%Y/%m/', verbose_name='圖片')),
                ('language', models.CharField(choices=[('plaintext', '純文字'), ('bash', 'Command Line / Bash'), ('python', 'Python'), ('csharp', 'C#'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript'), ('sql', 'SQL'), ('java', 'Java'), ('cpp', 'C++'), ('json', 'JSON'), ('xml', 'XML'), ('yaml', 'YAML'), ('markdown', 'Markdown')], default='plaintext', help_text='僅用於程式碼片段', max_length=20, verbose_name='程式語言')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='說明文字')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='TutorialHub.tutorialstep', verbose_name='步驟')),
            ],
            options={
                'verbose_name': '步驟片段',
                'verbose_name_plural': '步驟片段',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='TutorialHub.tutorialstep', verbose_name='步驟'),
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seconds', models.PositiveIntegerField(default=0, verbose_name='總閱讀秒數')),
                ('first_read_at', models.DateTimeField(auto_now_add=True, verbose_name='首次閱讀時間')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='最後閱讀時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_reading_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_logs', to='TutorialHub.tutorial', verbose_name='教材')),
            ],
            options={
                'verbose_name': '閱讀記錄',
                'verbose_name_plural': '閱讀記錄',
                'ordering': ['-last_read_at'],
                'unique_together': {('tutorial', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TutorialMaintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', '創建者'), ('maintainer', '維護者')], default='maintainer', max_length=20, verbose_name='角色')),
                ('contribution_score', models.IntegerField(default=0, help_text='用於排序貢獻者', validators=[django.core.validators.MinValueValidator(0)], verbose_name='貢獻度分數')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainers', to='TutorialHub.tutorial', verbose_name='教材')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_contributions', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '教材維護者',
                'verbose_name_plural': '教材維護者',
                'ordering': ['-contribution_score', 'joined_at'],
                'unique_together': {('tutorial', 'user')},
            },
        ),
    ]
