# Generated by Django 5.2.8 on 2025-12-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsnippet',
            name='link_text',
            field=models.CharField(blank=True, help_text='顯示的連結文字', max_length=200, null=True, verbose_name='連結文字'),
        ),
        migrations.AddField(
            model_name='stepsnippet',
            name='link_url',
            field=models.URLField(blank=True, help_text='超連結的目標網址', null=True, verbose_name='連結網址'),
        ),
        migrations.AlterField(
            model_name='stepsnippet',
            name='snippet_type',
            field=models.CharField(choices=[('text', '文字'), ('image', '圖片'), ('code', '程式碼'), ('link', '超連結')], default='text', max_length=10, verbose_name='片段類型'),
        ),
    ]
