# Generated by Django 5.2.9 on 2026-01-06 03:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('slug', models.CharField(choices=[('internal', '公司/部門工具'), ('external', '外部工具'), ('notes', '軟體使用筆記')], max_length=50, unique=True, verbose_name='分類代碼')),
                ('description', models.TextField(blank=True, verbose_name='分類說明')),
                ('order', models.IntegerField(default=0, help_text='數字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='工具名稱')),
                ('image', models.ImageField(upload_to='aitools/images/%Y/%m/', verbose_name='圖片')),
                ('url', models.URLField(blank=True, verbose_name='網址')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='簡介')),
                ('extra_info', models.TextField(blank=True, verbose_name='其他說明')),
                ('note_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='當分類為「軟體使用筆記」時使用', verbose_name='筆記內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏數')),
                ('like_count', models.IntegerField(default=0, verbose_name='點讚數')),
                ('view_count', models.IntegerField(default=0, verbose_name='瀏覽數')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_aitools', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='AIToolsHub.category', verbose_name='分類')),
                ('tags', models.ManyToManyField(blank=True, related_name='tools', to='AIToolsHub.tag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': 'AI 工具',
                'verbose_name_plural': 'AI 工具',
                'ordering': ['-favorite_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='AIToolsHub.comment', verbose_name='父留言')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AIToolsHub.aitool', verbose_name='工具')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aitool_comments', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='AIToolsHub.aitool', verbose_name='工具')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aitool_favorites', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'ordering': ['-created_at'],
                'unique_together': {('tool', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='點讚時間')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='AIToolsHub.aitool', verbose_name='工具')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aitool_likes', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '點讚',
                'verbose_name_plural': '點讚',
                'ordering': ['-created_at'],
                'unique_together': {('tool', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='瀏覽時間')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='AIToolsHub.aitool', verbose_name='工具')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aitool_views', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '瀏覽記錄',
                'verbose_name_plural': '瀏覽記錄',
                'ordering': ['-viewed_at'],
                'unique_together': {('tool', 'user')},
            },
        ),
    ]
