# Generated by Django - AIToolsHub initial categories

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """建立預設的三個分類"""
    Category = apps.get_model('AIToolsHub', 'Category')
    
    categories = [
        {'name': '公司/部門工具', 'slug': 'internal', 'description': '公司內部或部門自行開發的工具', 'order': 1},
        {'name': '外部工具', 'slug': 'external', 'description': '外部第三方的 AI 工具與服務', 'order': 2},
    ]
    
    for cat_data in categories:
        Category.objects.get_or_create(
            slug=cat_data['slug'],
            defaults=cat_data
        )


def reverse_categories(apps, schema_editor):
    """反向操作：刪除預設分類"""
    Category = apps.get_model('AIToolsHub', 'Category')
    Category.objects.filter(slug__in=['internal', 'external']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('AIToolsHub', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_categories),
    ]
