# Generated by Django 5.2.9 on 2026-01-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIToolsHub', '0003_comment_is_anonymous_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
    ]
