# Generated by Django 5.2.9 on 2026-01-06 07:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIToolsHub', '0004_comment_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitool',
            name='note_content',
        ),
        migrations.AlterField(
            model_name='aitool',
            name='extra_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='其他說明'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[('internal', '公司/部門工具'), ('external', '外部工具')], max_length=50, unique=True, verbose_name='分類代碼'),
        ),
    ]
