# Generated by Django 5.2.9 on 2026-01-16 07:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL 名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '資料標籤',
                'verbose_name_plural': '資料標籤',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名稱')),
                ('icon', models.CharField(default='📍', help_text='Emoji 或 CSS class 名稱', max_length=50, verbose_name='圖示')),
                ('color', models.CharField(default='#0000FF', help_text='Hex 色碼，例如 #FF0000', max_length=7, verbose_name='標記顏色')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('opensearch_pattern', models.CharField(blank=True, help_text='對應的 OpenSearch 索引模式，例如 sinoproject*', max_length=100, verbose_name='OpenSearch 索引模式')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '資料分類',
                'verbose_name_plural': '資料分類',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='經度')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='區域')),
                ('country', models.CharField(default='台灣', max_length=100, verbose_name='國家')),
                ('geometry_type', models.CharField(choices=[('POINT', '點'), ('LINE', '線'), ('POLYGON', '面'), ('MULTIPOINT', '多點')], default='POINT', max_length=20, verbose_name='幾何類型')),
                ('geometry_data', models.JSONField(blank=True, help_text='GeoJSON 格式的座標資料', null=True, verbose_name='幾何資料')),
                ('geo_hash', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='GeoHash')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='精確度(公尺)')),
                ('is_manually_adjusted', models.BooleanField(default=False, verbose_name='已手動調整')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '地理位置',
                'verbose_name_plural': '地理位置',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='GeoDataHub__latitud_6ed8fd_idx'), models.Index(fields=['geo_hash'], name='GeoDataHub__geo_has_4a359e_idx'), models.Index(fields=['city'], name='GeoDataHub__city_a5f9d0_idx'), models.Index(fields=['country'], name='GeoDataHub__country_f9ac92_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeoDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('source_type', models.CharField(choices=[('upload', '使用者上傳'), ('link', '外部連結'), ('opensearch', 'OpenSearch 資料')], max_length=20, verbose_name='來源類型')),
                ('file', models.FileField(blank=True, null=True, upload_to='geodatahub/%Y/%m/', verbose_name='檔案')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='檔案大小(bytes)')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='檔案類型')),
                ('external_url', models.URLField(blank=True, max_length=2000, verbose_name='外部連結')),
                ('opensearch_index', models.CharField(blank=True, max_length=200, verbose_name='OpenSearch 索引')),
                ('opensearch_doc_id', models.CharField(blank=True, max_length=200, verbose_name='OpenSearch 文件 ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='額外的結構化資料', verbose_name='中繼資料')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='geodatahub/thumbnails/%Y/%m/', verbose_name='縮圖')),
                ('is_visible', models.BooleanField(default=True, verbose_name='公開顯示')),
                ('is_featured', models.BooleanField(default=False, verbose_name='精選')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='GeoDataHub.geocategory', verbose_name='分類')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_data_sources', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('tags', models.ManyToManyField(blank=True, related_name='data_sources', to='GeoDataHub.datatag', verbose_name='標籤')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to='GeoDataHub.geolocation', verbose_name='地理位置')),
            ],
            options={
                'verbose_name': '地理資料來源',
                'verbose_name_plural': '地理資料來源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoDataView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='瀏覽時間')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='GeoDataHub.geodatasource', verbose_name='資料來源')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_data_views', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '瀏覽記錄',
                'verbose_name_plural': '瀏覽記錄',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['-viewed_at'], name='GeoDataHub__viewed__a07d4b_idx'), models.Index(fields=['source', '-viewed_at'], name='GeoDataHub__source__b60dec_idx'), models.Index(fields=['user', '-viewed_at'], name='GeoDataHub__user_id_41f263_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='geodatasource',
            index=models.Index(fields=['-created_at'], name='GeoDataHub__created_442f50_idx'),
        ),
        migrations.AddIndex(
            model_name='geodatasource',
            index=models.Index(fields=['source_type'], name='GeoDataHub__source__d9f043_idx'),
        ),
        migrations.AddIndex(
            model_name='geodatasource',
            index=models.Index(fields=['category'], name='GeoDataHub__categor_30c6ee_idx'),
        ),
        migrations.AddIndex(
            model_name='geodatasource',
            index=models.Index(fields=['is_visible', '-created_at'], name='GeoDataHub__is_visi_31c92e_idx'),
        ),
        migrations.AddIndex(
            model_name='geodatasource',
            index=models.Index(fields=['opensearch_index', 'opensearch_doc_id'], name='GeoDataHub__opensea_c3301e_idx'),
        ),
    ]
