# Generated by Django 5.2.9 on 2026-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoDataHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(unique=True, verbose_name='查詢字串')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='地理編碼結果')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否成功')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失敗次數')),
                ('last_attempt', models.DateTimeField(auto_now=True, verbose_name='最後嘗試時間')),
            ],
            options={
                'verbose_name': '地理編碼快取',
                'verbose_name_plural': '地理編碼快取',
                'indexes': [models.Index(fields=['query'], name='GeoDataHub__query_cc9902_idx')],
            },
        ),
    ]
