# Generated by Django 5.2.9 on 2026-01-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoDataHub', '0002_geocodingcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('metadata_sync', '元數據同步 (OpenSearch -> DB)'), ('location_resolve', '地理位置解析 (地址/圖號 -> 座標)'), ('cleanup', '資料清理與維護')], max_length=50, verbose_name='任務類型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('success', '已完成'), ('partial', '部分完成'), ('failed', '失敗'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='狀態')),
                ('total_expected', models.IntegerField(default=0, verbose_name='預期總數')),
                ('processed_count', models.IntegerField(default=0, verbose_name='已處理數')),
                ('created_count', models.IntegerField(default=0, verbose_name='新增數')),
                ('updated_count', models.IntegerField(default=0, verbose_name='更新數')),
                ('error_count', models.IntegerField(default=0, verbose_name='錯誤數')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳過數')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('log_details', models.JSONField(blank=True, default=dict, verbose_name='詳細記錄')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
            ],
            options={
                'verbose_name': '資料同步日誌',
                'verbose_name_plural': '資料同步日誌',
                'ordering': ['-start_time'],
            },
        ),
    ]
