# Generated by Django 5.2.10 on 2026-01-19 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoDataHub', '0003_geosynclog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('view_detail', '查看詳情'), ('copy_unc', '複製 UNC 路徑')], default='view_detail', max_length=20, verbose_name='點擊類型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeoDataHub.geocategory', verbose_name='分類')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='GeoDataHub.geodatasource', verbose_name='資料來源')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_click_logs', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '點擊記錄',
                'verbose_name_plural': '點擊記錄',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='GeoDataHub__created_44bfeb_idx'), models.Index(fields=['source', '-created_at'], name='GeoDataHub__source__b57b8f_idx'), models.Index(fields=['user', '-created_at'], name='GeoDataHub__user_id_e37328_idx')],
            },
        ),
    ]
