# Generated by Django 5.2.12 on 2026-03-17 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoProAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配件名稱')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='庫存數量')),
                ('rented_quantity', models.PositiveIntegerField(default=0, verbose_name='已出借數量')),
            ],
            options={
                'verbose_name': 'GoPro配件',
                'verbose_name_plural': 'GoPro配件庫存',
            },
        ),
        migrations.CreateModel(
            name='GoProRentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('department', models.CharField(max_length=100, verbose_name='租借部門')),
                ('borrower', models.CharField(max_length=50, verbose_name='租借人')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('equipment', models.CharField(max_length=100, verbose_name='設備')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': 'GoPro租借紀錄',
                'verbose_name_plural': 'GoPro租借紀錄',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VrComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='設備編號')),
                ('specifications', models.TextField(blank=True, verbose_name='設備規格')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('local_account', models.CharField(blank=True, max_length=50, verbose_name='本機帳號')),
                ('local_password', models.CharField(blank=True, max_length=50, verbose_name='本機密碼')),
            ],
            options={
                'verbose_name': 'VR專用電腦',
                'verbose_name_plural': 'VR專用電腦清單',
            },
        ),
        migrations.CreateModel(
            name='XrEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='設備名稱')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='設備編號')),
                ('specifications', models.TextField(blank=True, verbose_name='設備規格')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('status', models.CharField(choices=[('available', '在庫'), ('rented', '已出借'), ('maintenance', '維修中'), ('retired', '已退役')], default='available', max_length=20, verbose_name='租用狀態')),
            ],
            options={
                'verbose_name': 'XR設備',
                'verbose_name_plural': 'XR設備清單',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='XrSupportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('department', models.CharField(max_length=100, verbose_name='租借部門')),
                ('reason', models.TextField(blank=True, verbose_name='原因')),
                ('nature', models.CharField(choices=[('rental', '純租借'), ('support', '技術支援'), ('event', '活動配合')], max_length=20, verbose_name='租借性質')),
                ('equipment_count', models.PositiveIntegerField(default=0, verbose_name='研資設備(台)')),
                ('support_people', models.PositiveIntegerField(default=0, verbose_name='研資支援(人)')),
                ('event_scale', models.PositiveIntegerField(default=0, verbose_name='活動規模(人)')),
                ('rented_equipments', models.ManyToManyField(blank=True, to='XrResource.xrequipment', verbose_name='租借設備')),
            ],
            options={
                'verbose_name': 'XR支援事務',
                'verbose_name_plural': 'XR支援事務紀錄',
                'ordering': ['-date'],
            },
        ),
    ]
