# Generated by Django 5.2.12 on 2026-03-17 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='種類名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.CharField(default='fas fa-box', help_text='如: fas fa-laptop', max_length=50, verbose_name='圖示線索')),
            ],
            options={
                'verbose_name': '設備種類',
                'verbose_name_plural': '設備種類管理',
            },
        ),
        migrations.AddField(
            model_name='xrequipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='XrResource.equipmentcategory', verbose_name='設備種類'),
        ),
    ]
