# Generated by Django 5.2.12 on 2026-03-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0002_equipmentcategory_xrequipment_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoProAccessory',
        ),
        migrations.DeleteModel(
            name='VrComputer',
        ),
        migrations.AlterModelOptions(
            name='xrequipment',
            options={'ordering': ['serial_number'], 'verbose_name': '資源設備', 'verbose_name_plural': '資源設備清單'},
        ),
        migrations.AddField(
            model_name='xrequipment',
            name='section',
            field=models.CharField(choices=[('vr', 'VR 專區'), ('gopro', 'GoPro 專區')], default='vr', max_length=20, verbose_name='專區'),
        ),
        migrations.AlterField(
            model_name='xrequipment',
            name='status',
            field=models.CharField(choices=[('available', '在庫'), ('rented', '已出借'), ('maintenance', '維修中'), ('retired', '已退役')], default='available', max_length=20, verbose_name='狀態'),
        ),
    ]
