# Generated by Django 5.2.12 on 2026-03-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0003_delete_goproaccessory_delete_vrcomputer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='設備編號'),
        ),
    ]
