# Generated by Django 5.2.12 on 2026-03-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0004_alter_xrequipment_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrBulkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('vr', 'VR 專區'), ('gopro', 'GoPro 專區')], default='vr', max_length=20, verbose_name='專區')),
                ('name', models.CharField(max_length=100, verbose_name='項目名稱')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='總數量')),
                ('available_count', models.PositiveIntegerField(default=0, verbose_name='在庫數量')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '數量統計設備',
                'verbose_name_plural': '數量統計設備',
                'ordering': ['name'],
            },
        ),
    ]
