# Generated by Django 5.2.12 on 2026-03-19 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0005_xrbulkitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrRentalBulkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='租借數量')),
                ('bulk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XrResource.xrbulkitem')),
            ],
        ),
        migrations.CreateModel(
            name='XrRentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(verbose_name='活動日期')),
                ('rental_start', models.DateField(verbose_name='租借起始日期')),
                ('rental_end', models.DateField(verbose_name='租借結束日期')),
                ('department', models.CharField(max_length=100, verbose_name='部門')),
                ('borrower_name', models.CharField(max_length=50, verbose_name='租借人姓名')),
                ('borrower_id', models.CharField(max_length=50, verbose_name='租借人員工編號')),
                ('activity_name', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('reason', models.TextField(blank=True, verbose_name='租借原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_items', models.ManyToManyField(blank=True, through='XrResource.XrRentalBulkItem', to='XrResource.xrbulkitem', verbose_name='租借配件')),
                ('equipments', models.ManyToManyField(blank=True, to='XrResource.xrequipment', verbose_name='租借設備')),
            ],
            options={
                'verbose_name': '設備租借登記',
                'verbose_name_plural': '設備租借登記',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='xrrentalbulkitem',
            name='rental_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XrResource.xrrentalrecord'),
        ),
    ]
