# Generated by Django 5.2.12 on 2026-03-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0006_xrrentalbulkitem_xrrentalrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrrentalrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待核核'), ('approved', '已核准'), ('rejected', '已拒絕'), ('returned', '已歸還')], default='pending', max_length=20, verbose_name='單據狀態'),
        ),
        migrations.AlterField(
            model_name='xrequipment',
            name='status',
            field=models.CharField(choices=[('available', '在庫'), ('reserved', '預約中'), ('rented', '已出借'), ('maintenance', '維修中'), ('retired', '已退役')], default='available', max_length=20, verbose_name='狀態'),
        ),
    ]
