# Generated by Django 5.2.12 on 2026-03-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0007_xrrentalrecord_status_alter_xrequipment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrbulkitem',
            name='reserved_count',
            field=models.PositiveIntegerField(default=0, verbose_name='待扣數量'),
        ),
    ]
