# Generated by Django 5.2.12 on 2026-03-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0008_xrbulkitem_reserved_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrrentalbulkitem',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='是否已歸還'),
        ),
    ]
