# Generated by Django 5.2.12 on 2026-03-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0009_xrrentalbulkitem_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrrentalrecord',
            name='status',
            field=models.CharField(choices=[('pending', '待核准'), ('approved', '已核准'), ('rejected', '已拒絕'), ('returned', '已歸還')], default='pending', max_length=20, verbose_name='單據狀態'),
        ),
    ]
