# Generated by Django 5.2.12 on 2026-03-19 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0010_alter_xrrentalrecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='xrbulkitem',
            name='available_count',
            field=models.PositiveIntegerField(default=0, verbose_name='庫存數量'),
        ),
        migrations.AlterField(
            model_name='xrequipment',
            name='status',
            field=models.CharField(choices=[('available', '庫存'), ('reserved', '預約'), ('rented', '出借'), ('maintenance', '維修'), ('retired', '退役')], default='available', max_length=20, verbose_name='狀態'),
        ),
        migrations.CreateModel(
            name='XrUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理權限'), ('user', '一般使用者')], default='user', max_length=20, verbose_name='權限角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者權限設定',
                'verbose_name_plural': '使用者權限管理',
            },
        ),
    ]
