# Generated by Django 5.2.12 on 2026-03-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0011_alter_xrbulkitem_available_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrrentalrecord',
            name='return_notes',
            field=models.TextField(blank=True, verbose_name='歸還備註'),
        ),
    ]
