# Generated by Django 5.2.12 on 2026-03-19 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0012_xrrentalrecord_return_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='性質名稱')),
            ],
            options={
                'verbose_name': '租借性質',
                'verbose_name_plural': '租借性質管理',
            },
        ),
        migrations.AddField(
            model_name='xrrentalrecord',
            name='nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='XrResource.rentalnature', verbose_name='租借性質'),
        ),
    ]
