# Generated by Django 5.2.12 on 2026-03-24 09:28

import django.db.models.deletion
from django.db import migrations, models


# 用於暫放 M2M 資料的清單
_m2m_data_buffer = []

def save_m2m_data(apps, schema_editor):
    global _m2m_data_buffer
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("SELECT xrrentalrecord_id, xrequipment_id FROM XrResource_xrrentalrecord_equipments")
            _m2m_data_buffer = cursor.fetchall()
        except Exception:
            _m2m_data_buffer = []

def restore_m2m_data(apps, schema_editor):
    global _m2m_data_buffer
    XrRentalRecord = apps.get_model('XrResource', 'XrRentalRecord')
    XrRentalEquipment = apps.get_model('XrResource', 'XrRentalEquipment')
    
    for rental_id, equip_id in _m2m_data_buffer:
        try:
            rental = XrRentalRecord.objects.get(id=rental_id)
            is_returned = (rental.status == 'returned')
            XrRentalEquipment.objects.get_or_create(
                rental_record_id=rental_id,
                equipment_id=equip_id,
                defaults={'is_returned': is_returned}
            )
        except Exception:
            continue

class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0013_rentalnature_xrrentalrecord_nature'),
    ]

    operations = [
        migrations.CreateModel(
            name='XrRentalEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否已歸還')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XrResource.xrequipment')),
                ('rental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XrResource.xrrentalrecord')),
            ],
            options={
                'verbose_name': '租借設備狀態',
                'verbose_name_plural': '租借設備狀態',
            },
        ),
        # 1. 先備份資料
        migrations.RunPython(save_m2m_data),
        # 2. 移除舊欄位 (包含移除舊表)
        migrations.RemoveField(
            model_name='xrrentalrecord',
            name='equipments',
        ),
        # 3. 新增帶有 through 的欄位
        migrations.AddField(
            model_name='xrrentalrecord',
            name='equipments',
            field=models.ManyToManyField(blank=True, through='XrResource.XrRentalEquipment', to='XrResource.xrequipment', verbose_name='租借設備'),
        ),
        # 4. 還原資料
        migrations.RunPython(restore_m2m_data),
    ]
