# Generated by Django 5.2.12 on 2026-03-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0014_xrrentalequipment_alter_xrrentalrecord_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrrentalrecord',
            name='attachment',
            field=models.FileField(blank=True, help_text='可上傳照片(pdf或圖片)', null=True, upload_to='rental_attachments/', verbose_name='附件'),
        ),
    ]
