# Generated by Django 5.2.12 on 2026-03-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0015_xrrentalrecord_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrrentalrecord',
            name='attachment',
        ),
        migrations.AddField(
            model_name='xrrentalrecord',
            name='return_attachment',
            field=models.FileField(blank=True, help_text='點交時可上傳照片或 PDF 佐證資料', null=True, upload_to='return_attachments/', verbose_name='點交附件'),
        ),
    ]
