# Generated by Django 5.2.12 on 2026-03-25 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0016_remove_xrrentalrecord_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrrentalrecord',
            name='return_attachment',
        ),
        migrations.CreateModel(
            name='XrRentalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='return_attachments/', verbose_name='附件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rental_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='XrResource.xrrentalrecord')),
            ],
            options={
                'verbose_name': '點交佐證附件',
                'verbose_name_plural': '點交佐證附件',
            },
        ),
    ]
