# Generated by Django 5.2.12 on 2026-03-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0017_remove_xrrentalrecord_return_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xruserprofile',
            name='receive_notifications',
            field=models.BooleanField(default=True, verbose_name='接收租借通知信'),
        ),
    ]
