# Generated by Django 5.2.12 on 2026-03-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0018_xruserprofile_receive_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xruserprofile',
            name='receive_notifications',
            field=models.BooleanField(default=False, verbose_name='接收租借通知信'),
        ),
    ]
