# Generated by Django 5.2.12 on 2026-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XrResource', '0019_alter_xruserprofile_receive_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xruserprofile',
            name='receive_notifications',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='接收租借通知信'),
        ),
    ]
