# Generated by Django 5.2.8 on 2025-12-08 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='主題名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '主題',
                'verbose_name_plural': '主題',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='標題')),
                ('date', models.DateTimeField(verbose_name='發布日期')),
                ('url', models.URLField(max_length=1000, verbose_name='網址')),
                ('source', models.CharField(max_length=255, verbose_name='資料來源')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取時間')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='NewsSubscriber.topic', verbose_name='所屬主題')),
            ],
            options={
                'verbose_name': '新聞項目',
                'verbose_name_plural': '新聞項目',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, verbose_name='關鍵字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='NewsSubscriber.topic', verbose_name='所屬主題')),
            ],
            options={
                'verbose_name': '關鍵字',
                'verbose_name_plural': '關鍵字',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='摘要內容')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='摘要日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='NewsSubscriber.topic', verbose_name='所屬主題')),
            ],
            options={
                'verbose_name': '每日摘要',
                'verbose_name_plural': '每日摘要',
                'ordering': ['-date'],
            },
        ),
    ]
