# Generated by Django 5.2.8 on 2025-12-08 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSubscriber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='接收信箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='訂閱時間')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='NewsSubscriber.topic', verbose_name='訂閱主題')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='訂閱使用者')),
            ],
            options={
                'verbose_name': '訂閱',
                'verbose_name_plural': '訂閱',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
