# Generated by Django 5.2.8 on 2025-12-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSubscriber', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='news_count',
            field=models.IntegerField(default=0, verbose_name='新聞數量'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content',
            field=models.TextField(blank=True, verbose_name='新聞內容'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='summary',
            field=models.TextField(blank=True, verbose_name='新聞摘要'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('topic', 'date')},
        ),
    ]
