# Generated by Django 5.2.8 on 2025-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSubscriber', '0003_dailysummary_news_count_newsitem_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField()),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('tag', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
