# Generated by Django 5.2.8 on 2025-12-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSubscriber', '0004_openairesponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='news_source_html',
            field=models.TextField(blank=True, verbose_name='新聞來源HTML'),
        ),
    ]
