# Generated by Django 5.2.10 on 2026-01-21 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='委員姓名')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='所屬單位')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='專長領域')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '評審委員',
                'verbose_name_plural': '評審委員',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='標案名稱')),
                ('bid_number', models.CharField(blank=True, max_length=100, verbose_name='標案編號')),
                ('bid_date', models.DateField(blank=True, null=True, verbose_name='開標日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已投標'), ('won', '得標'), ('lost', '未得標'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='狀態')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '標案',
                'verbose_name_plural': '標案',
                'ordering': ['-bid_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_committees', to='BidQA.bid', verbose_name='標案')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_committees', to='BidQA.committee', verbose_name='委員')),
            ],
            options={
                'verbose_name': '標案委員',
                'verbose_name_plural': '標案委員',
                'unique_together': {('bid', 'committee')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='提問內容')),
                ('answer', models.TextField(blank=True, verbose_name='回答內容')),
                ('reference', models.TextField(blank=True, verbose_name='參考資料')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('bid_committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='BidQA.bidcommittee', verbose_name='標案委員')),
            ],
            options={
                'verbose_name': '問答記錄',
                'verbose_name_plural': '問答記錄',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
