# Generated by Django 5.2.10 on 2026-01-21 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidQA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bidqa/files/%Y/%m/', verbose_name='檔案')),
                ('filename', models.CharField(max_length=255, verbose_name='檔案名稱')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='說明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='BidQA.bid', verbose_name='標案')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidqa_files_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '標案文件',
                'verbose_name_plural': '標案文件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='下載時間')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 位址')),
                ('downloaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidqa_downloads', to=settings.AUTH_USER_MODEL, verbose_name='下載者')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='BidQA.bidfile', verbose_name='檔案')),
            ],
            options={
                'verbose_name': '下載記錄',
                'verbose_name_plural': '下載記錄',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
