# Generated by Django 5.2.10 on 2026-01-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidQA', '0002_bidfile_filedownloadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('won', '得標'), ('lost', '未得標'), ('failed', '流標'), ('unannounced', '未公布')], default='unannounced', max_length=20, verbose_name='狀態'),
        ),
    ]
