# Generated by Django 5.2.9 on 2026-01-26 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文字'), ('image', '圖片'), ('file', '檔案'), ('system', '系統訊息')], default='text', max_length=10, verbose_name='訊息類型')),
                ('content', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發送時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='發送者')),
            ],
            options={
                'verbose_name': '聊天訊息',
                'verbose_name_plural': '聊天訊息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files/%Y/%m/', verbose_name='檔案')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='檔案大小')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='檔案類型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='SinoChat.chatmessage', verbose_name='訊息')),
            ],
            options={
                'verbose_name': '聊天檔案',
                'verbose_name_plural': '聊天檔案',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='聊天室名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('visibility', models.CharField(choices=[('public', '公開 - 所有人可加入'), ('private', '私人 - 僅邀請者可加入')], default='public', max_length=10, verbose_name='可見性')),
                ('avatar_color', models.CharField(default='#C41E3A', max_length=7, verbose_name='頭像顏色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chatrooms', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='SinoChat.chatroom', verbose_name='聊天室'),
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理員'), ('member', '成員')], default='member', max_length=10, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最後讀取時間')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='SinoChat.chatroom', verbose_name='聊天室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '聊天室成員',
                'verbose_name_plural': '聊天室成員',
                'unique_together': {('room', 'user')},
            },
        ),
    ]
