# Generated by Django 5.2.9 on 2026-01-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(help_text='例如: VOL_20260108', max_length=100, unique=True, verbose_name='資料夾名稱')),
                ('total_size', models.BigIntegerField(default=0, help_text='此卷冊中所有檔案的總大小', verbose_name='目前大小(bytes)')),
                ('max_size', models.BigIntegerField(default=4294967296, verbose_name='大小上限(bytes)')),
                ('status', models.CharField(choices=[('STAGING', '暫存中'), ('CLOSED', '已封閉'), ('ARCHIVED', '已封存')], default='STAGING', max_length=20, verbose_name='狀態')),
                ('manifest_data', models.JSONField(blank=True, default=dict, help_text='記錄原始路徑與 UUID 檔名的對應關係', verbose_name='清單資料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='封閉時間')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='封存時間')),
            ],
            options={
                'verbose_name': '封存資料夾',
                'verbose_name_plural': '封存資料夾',
                'ordering': ['-created_at'],
            },
        ),
    ]
