# Generated by Django 4.2.11 on 2024-05-17 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_single', models.BooleanField(blank=True, default=False, verbose_name='已同意使用平台')),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True, verbose_name='小超級使用者')),
                ('emp_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('emp_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='電子郵件')),
                ('emp_dept', models.CharField(blank=True, max_length=20, null=True, verbose_name='部門')),
                ('emp_company', models.CharField(blank=True, max_length=20, null=True, verbose_name='公司')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
