# Generated by Django 4.2.11 on 2024-05-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='agreed_single',
        ),
    ]
