# Generated by Django 5.2.8 on 2025-12-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_remove_userprofile_agreed_single'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='自我介紹'),
        ),
    ]
