# Generated by Django 5.2.9 on 2026-02-10 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignConsistency', '0004_comparisonissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonissue',
            name='issue_type',
            field=models.CharField(choices=[('unmatched_budget', 'Budget only'), ('unmatched_quantity', 'Quantity only'), ('name_variance', '名稱差異'), ('unit_mismatch', 'Unit mismatch'), ('qty_mismatch', 'Quantity mismatch'), ('low_confidence', 'Low confidence match')], max_length=32),
        ),
        migrations.CreateModel(
            name='IntermediateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='唯一識別碼，格式: {reference}_{file_id}_{row}', max_length=128, unique=True)),
                ('item_name', models.CharField(help_text='原始名稱，保留原始文字', max_length=500)),
                ('standard_name', models.CharField(db_index=True, help_text='正規化名稱：去除空格、全半型轉換後的清潔名稱', max_length=500)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='數量', max_digits=16, null=True)),
                ('unit', models.CharField(blank=True, help_text='單位', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='單價，供未來比對總價使用', max_digits=16, null=True)),
                ('reference', models.CharField(choices=[('budget', '預算書'), ('quantity', '數量計算書'), ('spec', '規範附錄')], help_text='來源標記：預算書 / 數量計算書 / 規範附錄', max_length=32)),
                ('item_no', models.CharField(blank=True, help_text='原始項次編號', max_length=100)),
                ('extra', models.JSONField(blank=True, help_text='擴充欄位（sheet 名稱、XML 路徑等）', null=True)),
                ('name_tokens', models.JSONField(blank=True, help_text='預計算的 token 清單，加速模糊比對', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_items', to='DesignConsistency.project')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intermediate_items', to='DesignConsistency.projectfile')),
            ],
            options={
                'ordering': ['reference', 'item_no', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_method', models.CharField(choices=[('exact', '精準匹配'), ('fuzzy', '模糊匹配'), ('token', 'Token 匹配'), ('item_no', '項次匹配')], help_text='匹配方式', max_length=32)),
                ('score', models.IntegerField(default=0, help_text='匹配分數 (0-100)')),
                ('is_name_consistent', models.BooleanField(default=False, help_text='名稱是否一致')),
                ('is_unit_consistent', models.BooleanField(default=False, help_text='單位是否一致')),
                ('is_qty_consistent', models.BooleanField(default=False, help_text='數量是否一致')),
                ('detail', models.JSONField(blank=True, help_text='差異細節（名稱 diff、數量差異等）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_a', models.ForeignKey(help_text='比對項 A', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='DesignConsistency.intermediateitem')),
                ('item_b', models.ForeignKey(help_text='比對項 B', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='DesignConsistency.intermediateitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='DesignConsistency.project')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_results', to='DesignConsistency.comparisonrun')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='intermediateitem',
            index=models.Index(fields=['project', 'reference'], name='idx_ii_proj_ref'),
        ),
        migrations.AddIndex(
            model_name='intermediateitem',
            index=models.Index(fields=['project', 'standard_name'], name='idx_ii_proj_stdname'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['project', 'match_method'], name='idx_mr_proj_method'),
        ),
    ]
