# Generated by Django 5.2.10 on 2026-01-14 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=20, unique=True, verbose_name='站碼')),
                ('name', models.CharField(max_length=100, verbose_name='站名')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='縣市')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='區域')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='經度')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='高度(公尺)')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='設站日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '氣象站',
                'verbose_name_plural': '氣象站',
                'ordering': ['station_code'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_date', models.DateField(verbose_name='觀測日期')),
                ('station_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='測站氣壓(hPa)')),
                ('sea_level_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='海平面氣壓(hPa)')),
                ('max_station_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='最高測站氣壓(hPa)')),
                ('min_station_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='最低測站氣壓(hPa)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平均氣溫(°C)')),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最高氣溫(°C)')),
                ('max_temp_time', models.CharField(blank=True, max_length=50, verbose_name='最高氣溫時間')),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最低氣溫(°C)')),
                ('min_temp_time', models.CharField(blank=True, max_length=50, verbose_name='最低氣溫時間')),
                ('relative_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='相對濕度(%)')),
                ('min_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最小相對濕度(%)')),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='平均風速(m/s)')),
                ('wind_direction', models.CharField(blank=True, max_length=20, verbose_name='平均風向')),
                ('max_wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='最大陣風(m/s)')),
                ('max_wind_direction', models.CharField(blank=True, max_length=20, verbose_name='最大陣風風向')),
                ('precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='降水量(mm)')),
                ('precipitation_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='降水時數(hr)')),
                ('sunshine_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='日照時數(hr)')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始資料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='CWA_Data_Scraper.weatherstation', verbose_name='氣象站')),
            ],
            options={
                'verbose_name': '月報表資料',
                'verbose_name_plural': '月報表資料',
                'ordering': ['-obs_date'],
                'unique_together': {('station', 'obs_date')},
            },
        ),
    ]
