# Generated by Django 5.2.10 on 2026-01-27 00:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='電話')),
                ('note', models.TextField(blank=True, verbose_name='備註/簡歷')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '應徵者',
                'verbose_name_plural': '應徵者資料',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '題目類別',
                'verbose_name_plural': '題目類別',
            },
        ),
        migrations.CreateModel(
            name='AdminWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_whitelist_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理員')),
            ],
            options={
                'verbose_name': '管理員白名單',
                'verbose_name_plural': '管理員白名單',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='題目內容')),
                ('question_type', models.CharField(choices=[('single', '單選題'), ('boolean', '是非題')], default='single', max_length=10, verbose_name='題目類型')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='選項 (JSON)')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='正確答案')),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='難度 (1-5)')),
                ('points', models.IntegerField(default=10, verbose_name='分數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='InterviewAssessment.questioncategory', verbose_name='類別')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題目庫',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='試卷標題')),
                ('description', models.TextField(blank=True, verbose_name='試卷描述')),
                ('time_limit_minutes', models.IntegerField(default=30, verbose_name='測驗時間 (分鐘)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用中')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '試卷',
                'verbose_name_plural': '試卷管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='交卷時間')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='總分')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='InterviewAssessment.candidate', verbose_name='應徵者')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='InterviewAssessment.quiz', verbose_name='試卷')),
            ],
            options={
                'verbose_name': '測驗紀錄',
                'verbose_name_plural': '測驗紀錄',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewAssessment.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewAssessment.quiz')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz', 'question')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', through='InterviewAssessment.QuizQuestion', to='InterviewAssessment.question', verbose_name='包含題目'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(blank=True, max_length=255, verbose_name='選擇答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正確')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='InterviewAssessment.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InterviewAssessment.question')),
            ],
            options={
                'verbose_name': '作答明細',
                'verbose_name_plural': '作答明細',
            },
        ),
    ]
