# Generated by Django 5.2.10 on 2026-01-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewAssessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='max_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='滿分'),
        ),
    ]
