# Generated by Django 5.2.10 on 2026-02-03 03:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEmissionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='計算名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('trip_count', models.DecimalField(decimal_places=2, default=0, help_text='次/日', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='旅次產生量')),
                ('car_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='汽車延人公里')),
                ('electric_car_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電動車延人公里')),
                ('motorcycle_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='機車延人公里')),
                ('electric_motorcycle_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電動機車延人公里')),
                ('bus_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='公車延人公里')),
                ('intercity_bus_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='客運延人公里')),
                ('metro_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='捷運延人公里')),
                ('railway_passenger_km', models.DecimalField(decimal_places=2, default=0, help_text='延人公里', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='鐵路延人公里')),
                ('solar_area', models.DecimalField(decimal_places=2, default=0, help_text='m²', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='太陽能板設置面積')),
                ('solar_capacity_factor', models.DecimalField(decimal_places=4, default=0.15, help_text='0-1之間', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='太陽能容量因數')),
                ('wind_area', models.DecimalField(decimal_places=2, default=0, help_text='m²', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='風力發電設置面積')),
                ('wind_capacity_factor', models.DecimalField(decimal_places=4, default=0.25, help_text='0-1之間', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='風力容量因數')),
                ('recycled_water_volume', models.DecimalField(decimal_places=2, default=0, help_text='m³/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='回收水量')),
                ('waste_recycled_volume', models.DecimalField(decimal_places=2, default=0, help_text='噸/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='廢棄物回收量')),
            ],
            options={
                'verbose_name': '碳排放計算輸入',
                'verbose_name_plural': '碳排放計算輸入',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_factor', models.DecimalField(decimal_places=4, default=0.12, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='汽車排放係數')),
                ('electric_car_factor', models.DecimalField(decimal_places=4, default=0.055, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='電動車排放係數')),
                ('motorcycle_factor', models.DecimalField(decimal_places=4, default=0.065, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='機車排放係數')),
                ('electric_motorcycle_factor', models.DecimalField(decimal_places=4, default=0.025, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='電動機車排放係數')),
                ('bus_factor', models.DecimalField(decimal_places=4, default=0.045, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='公車排放係數')),
                ('intercity_bus_factor', models.DecimalField(decimal_places=4, default=0.05, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='客運排放係數')),
                ('metro_factor', models.DecimalField(decimal_places=4, default=0.02, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='捷運排放係數')),
                ('railway_factor', models.DecimalField(decimal_places=4, default=0.018, help_text='kg CO2e/延人公里', max_digits=10, verbose_name='鐵路排放係數')),
                ('solar_factor', models.DecimalField(decimal_places=4, default=0.45, help_text='kg CO2e/kWh', max_digits=10, verbose_name='太陽能減碳係數')),
                ('wind_factor', models.DecimalField(decimal_places=4, default=0.46, help_text='kg CO2e/kWh', max_digits=10, verbose_name='風力減碳係數')),
                ('water_recycling_factor', models.DecimalField(decimal_places=4, default=0.152, help_text='kg CO2e/m³', max_digits=10, verbose_name='自來水碳足跡')),
                ('waste_recycling_factor', models.DecimalField(decimal_places=4, default=1.23, help_text='kg CO2e/噸', max_digits=10, verbose_name='焚化爐碳足跡')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '全域碳排放係數設定',
                'verbose_name_plural': '全域碳排放係數設定',
            },
        ),
        migrations.CreateModel(
            name='CarbonEmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='汽車碳排量')),
                ('electric_car_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='電動車碳排量')),
                ('motorcycle_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='機車碳排量')),
                ('electric_motorcycle_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='電動機車碳排量')),
                ('private_vehicle_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='私人運具總碳排量')),
                ('bus_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='公車碳排量')),
                ('intercity_bus_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='客運碳排量')),
                ('metro_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='捷運碳排量')),
                ('railway_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='鐵路碳排量')),
                ('public_transport_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='大眾運具總碳排量')),
                ('solar_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='太陽能減碳量')),
                ('wind_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='風力減碳量')),
                ('renewable_energy_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='再生能源總減碳量')),
                ('water_recycling_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='回收水減碳量')),
                ('waste_recycling_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='廢棄物回收減碳量')),
                ('total_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='總碳排量')),
                ('total_reduction', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='總減碳量')),
                ('net_emission', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='淨碳排量')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='計算時間')),
                ('input_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='CarbonPLBC.carbonemissioninput', verbose_name='輸入數據')),
            ],
            options={
                'verbose_name': '碳排放計算結果',
                'verbose_name_plural': '碳排放計算結果',
            },
        ),
    ]
