# Generated by Django 5.2.10 on 2026-02-03 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonPLBC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemissioninput',
            name='avg_trip_distance',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='公里', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='平均旅次距離'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='bus_ratio',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='公車使用比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='car_ratio',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='私人運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='汽車使用比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='electric_car_ratio',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='私人運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電動車使用比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='electric_motorcycle_ratio',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='私人運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電動機車使用比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='intercity_bus_ratio',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='客運使用比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='metro_ratio',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='捷運使用比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='motorcycle_ratio',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='私人運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='機車使用比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='private_transport_ratio',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='% (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='使用私人運具比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='public_transport_ratio',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='% (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='使用大眾運具比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='railway_ratio',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='鐵路使用比例'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='bus_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='公車延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='car_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='汽車延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='electric_car_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電動車延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='electric_motorcycle_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='電動機車延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='intercity_bus_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='客運延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='metro_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='捷運延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='motorcycle_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='機車延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='railway_passenger_km',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='自動計算', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='鐵路延人公里'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='trip_count',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/日', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='混合使用旅次產生量'),
        ),
    ]
