# Generated by Django 5.2.10 on 2026-02-03 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonPLBC', '0002_carbonemissioninput_avg_trip_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='electric_car_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='electric_motorcycle_ratio',
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='bus_ratio',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='公車使用比例'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='car_ratio',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='私人運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='汽車使用比例'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='intercity_bus_ratio',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='客運使用比例'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='metro_ratio',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='捷運使用比例'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='motorcycle_ratio',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='私人運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='機車使用比例'),
        ),
        migrations.AlterField(
            model_name='carbonemissioninput',
            name='railway_ratio',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='大眾運具中的%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='鐵路使用比例'),
        ),
    ]
