# Generated by Django 5.2.10 on 2026-02-03 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonPLBC', '0003_remove_carbonemissioninput_electric_car_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='bus_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='car_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='intercity_bus_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='metro_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='motorcycle_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='private_transport_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='public_transport_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='railway_ratio',
        ),
        migrations.RemoveField(
            model_name='carbonemissioninput',
            name='trip_count',
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='bus_trip_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='公車年旅次量'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='car_trip_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='汽車年旅次量'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='intercity_bus_trip_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='客運年旅次量'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='metro_trip_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='捷運年旅次量'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='motorcycle_trip_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='機車年旅次量'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='railway_trip_volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='鐵路年旅次量'),
        ),
    ]
