# Generated by Django 5.2.10 on 2026-02-03 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonPLBC', '0004_remove_carbonemissioninput_bus_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemissioninput',
            name='private_transport_ratio',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='私人運具比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='public_transport_ratio',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='%', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='大眾運具比例'),
        ),
        migrations.AddField(
            model_name='carbonemissioninput',
            name='trip_count',
            field=models.DecimalField(decimal_places=2, default=0, help_text='次/年', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='混合使用旅次量'),
        ),
    ]
