# Generated by Django 5.2.10 on 2026-02-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonPLBC', '0005_carbonemissioninput_private_transport_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonemissionresult',
            name='mixed_private_emission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='混合私人碳排量'),
        ),
        migrations.AddField(
            model_name='carbonemissionresult',
            name='mixed_public_emission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='混合大眾碳排量'),
        ),
        migrations.AddField(
            model_name='carbonemissionresult',
            name='mixed_total_emission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='混合總碳排量'),
        ),
    ]
