# Generated by Django 5.2.9 on 2026-01-06 03:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名稱')),
                ('description', models.TextField(verbose_name='成就描述')),
                ('achievement_type', models.CharField(choices=[('LEVEL', '等級成就'), ('SKILL', '技能成就'), ('TRIAL', '試煉成就'), ('EQUIPMENT', '裝備成就'), ('SPECIAL', '特殊成就')], max_length=20, verbose_name='成就類型')),
                ('condition', models.JSONField(default=dict, help_text='例如：{"level": 10} 或 {"trials_completed": 50}', verbose_name='達成條件')),
                ('exp_reward', models.IntegerField(default=0, verbose_name='經驗值獎勵')),
                ('scroll_reward', models.IntegerField(default=0, verbose_name='卷軸獎勵')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rpg/achievements/', verbose_name='成就圖示')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就列表',
            },
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CIVIL', '土木戰士 (Civil Warrior)'), ('ME', '機電法師 (M&E Mage)'), ('SAFETY', '職安僧侶 (Safety Monk)')], max_length=10, unique=True, verbose_name='職業代碼')),
                ('name', models.CharField(max_length=50, verbose_name='職業名稱')),
                ('description', models.TextField(verbose_name='職業描述')),
                ('base_hp', models.IntegerField(default=3, verbose_name='基礎HP')),
                ('base_mp', models.IntegerField(default=100, verbose_name='基礎MP')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rpg/class_icons/', verbose_name='職業圖示')),
            ],
            options={
                'verbose_name': '職業',
                'verbose_name_plural': '職業列表',
            },
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名稱')),
                ('description', models.TextField(verbose_name='技能描述')),
                ('node_type', models.CharField(choices=[('ROOT', '根部（共同必修）'), ('CORE', '主幹（職業核心）'), ('ADVANCED', '枝葉（進階選修）')], max_length=20, verbose_name='節點類型')),
                ('icon_locked', models.ImageField(blank=True, null=True, upload_to='rpg/skill_icons/', verbose_name='未解鎖圖示')),
                ('icon_unlocked', models.ImageField(blank=True, null=True, upload_to='rpg/skill_icons/', verbose_name='已解鎖圖示')),
                ('position_x', models.IntegerField(default=0, help_text='技能樹視覺化位置', verbose_name='X座標')),
                ('position_y', models.IntegerField(default=0, help_text='技能樹視覺化位置', verbose_name='Y座標')),
                ('exp_reward', models.IntegerField(default=50, verbose_name='完成獎勵經驗值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('character_class', models.ForeignKey(blank=True, help_text='ROOT 類型可為空，表示所有職業共用', null=True, on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.characterclass', verbose_name='所屬職業')),
                ('parent_skills', models.ManyToManyField(blank=True, related_name='child_skills', to='EngineerRPG.skillnode', verbose_name='前置技能')),
            ],
            options={
                'verbose_name': '技能節點',
                'verbose_name_plural': '技能節點',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='題目內容')),
                ('question_type', models.CharField(choices=[('SINGLE', '單選題'), ('MULTIPLE', '多選題'), ('TRUEFALSE', '是非題')], max_length=20, verbose_name='題目類型')),
                ('options', models.JSONField(default=dict, help_text='格式: {"A": "選項1", "B": "選項2", ...}', verbose_name='選項')),
                ('correct_answer', models.JSONField(help_text='單選: "A", 多選: ["A", "B"], 是非: "T" or "F"', verbose_name='正確答案')),
                ('explanation', models.TextField(blank=True, verbose_name='詳解')),
                ('difficulty', models.CharField(choices=[('S', 'S級（最難）'), ('A', 'A級（困難）'), ('B', 'B級（中等）'), ('C', 'C級（簡單）')], default='B', max_length=1, verbose_name='難度')),
                ('tags', models.CharField(blank=True, help_text='多個標籤用逗號分隔，例如：鋼筋,法規,職安', max_length=200, verbose_name='標籤')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rpg/questions/', verbose_name='題目圖片')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('related_skills', models.ManyToManyField(blank=True, related_name='questions', to='EngineerRPG.skillnode', verbose_name='關聯技能')),
            ],
            options={
                'verbose_name': '題目',
                'verbose_name_plural': '題庫',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='裝備名稱')),
                ('description', models.TextField(verbose_name='裝備描述')),
                ('equipment_type', models.CharField(choices=[('HELMET', '頭盔（安全帽）'), ('ARMOR', '護甲（反光背心）'), ('BOOTS', '靴子（雨鞋）'), ('TOOL_UAV', '工具 - 無人機'), ('TOOL_CAMERA', '工具 - 環景相機'), ('TOOL_GLASSES', '工具 - 智慧眼鏡'), ('TOOL_APP', '工具 - 查驗APP')], max_length=20, verbose_name='裝備類型')),
                ('rarity', models.CharField(choices=[('COMMON', '普通'), ('RARE', '稀有'), ('EPIC', '史詩'), ('LEGENDARY', '傳說')], default='COMMON', max_length=20, verbose_name='稀有度')),
                ('hp_bonus', models.IntegerField(default=0, verbose_name='HP加成')),
                ('mp_bonus', models.IntegerField(default=0, verbose_name='MP加成')),
                ('skill_effect', models.CharField(blank=True, help_text='例如：上帝視角、透視眼、快速檢索', max_length=100, verbose_name='技能效果')),
                ('skill_description', models.TextField(blank=True, verbose_name='技能說明')),
                ('mp_cost', models.IntegerField(default=0, verbose_name='技能消耗MP')),
                ('required_level', models.IntegerField(default=1, verbose_name='需求等級')),
                ('max_enhancement', models.IntegerField(default=5, verbose_name='最大強化等級')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rpg/equipment_icons/', verbose_name='裝備圖示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_equipment', to='EngineerRPG.skillnode', verbose_name='解鎖技能')),
            ],
            options={
                'verbose_name': '裝備',
                'verbose_name_plural': '裝備列表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='課程標題')),
                ('description', models.TextField(verbose_name='課程描述')),
                ('content_type', models.CharField(choices=[('VIDEO', '影片'), ('PDF', 'PDF文件'), ('PPT', 'PowerPoint'), ('LINK', '外部連結')], max_length=10, verbose_name='內容類型')),
                ('content_url', models.URLField(max_length=500, verbose_name='內容網址')),
                ('content_file', models.FileField(blank=True, null=True, upload_to='rpg/courses/', verbose_name='內容檔案')),
                ('duration_minutes', models.IntegerField(default=30, verbose_name='課程時長（分鐘）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('skill_nodes', models.ManyToManyField(related_name='courses', to='EngineerRPG.skillnode', verbose_name='關聯技能')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程列表',
            },
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='試煉標題')),
                ('description', models.TextField(verbose_name='試煉描述')),
                ('trial_type', models.CharField(choices=[('DAILY', '每日副本'), ('PROMOTION', '升階試煉'), ('SPECIAL', '特殊活動')], max_length=20, verbose_name='試煉類型')),
                ('question_count', models.IntegerField(default=10, help_text='從題目集合中隨機抽取的數量', verbose_name='題目數量')),
                ('time_limit_minutes', models.IntegerField(default=30, verbose_name='時間限制（分鐘）')),
                ('required_level', models.IntegerField(default=1, verbose_name='需求等級')),
                ('exp_reward', models.IntegerField(default=100, verbose_name='經驗值獎勵')),
                ('is_daily', models.BooleanField(default=False, verbose_name='每日副本')),
                ('refresh_date', models.DateField(blank=True, null=True, verbose_name='刷新日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('equipment_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_rewards', to='EngineerRPG.equipment', verbose_name='裝備獎勵')),
                ('questions', models.ManyToManyField(related_name='trials', to='EngineerRPG.question', verbose_name='題目集合')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='required_for_trials', to='EngineerRPG.skillnode', verbose_name='需求技能')),
            ],
            options={
                'verbose_name': '試煉',
                'verbose_name_plural': '試煉列表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='員工編號')),
                ('role', models.CharField(choices=[('ADVENTURER', '冒險者'), ('MANAGER', '公會會長'), ('ADMIN', '創世神')], default='ADVENTURER', max_length=20, verbose_name='角色權限')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='等級')),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='經驗值')),
                ('hp', models.IntegerField(default=3, verbose_name='生命值')),
                ('mp', models.IntegerField(default=100, verbose_name='技能值')),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='rpg/avatars/', verbose_name='角色頭像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EngineerRPG.characterclass', verbose_name='職業')),
                ('equipped_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_armor', to='EngineerRPG.equipment', verbose_name='護甲')),
                ('equipped_helmet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_helmet', to='EngineerRPG.equipment', verbose_name='頭盔')),
                ('equipped_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool', to='EngineerRPG.equipment', verbose_name='工具')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rpg_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者檔案',
                'verbose_name_plural': '使用者檔案',
            },
        ),
        migrations.CreateModel(
            name='UserEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enhancement_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='強化等級')),
                ('is_equipped', models.BooleanField(default=False, verbose_name='是否裝備中')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='獲得時間')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.equipment')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='EngineerRPG.userprofile')),
            ],
            options={
                'verbose_name': '使用者裝備',
                'verbose_name_plural': '使用者裝備',
            },
        ),
        migrations.CreateModel(
            name='TrialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分數')),
                ('total_questions', models.IntegerField(verbose_name='總題數')),
                ('correct_answers', models.IntegerField(verbose_name='答對題數')),
                ('time_spent_seconds', models.IntegerField(verbose_name='花費時間（秒）')),
                ('answer_details', models.JSONField(default=dict, help_text='記錄每題的答案與正確性', verbose_name='答題詳情')),
                ('exp_gained', models.IntegerField(default=0, verbose_name='獲得經驗值')),
                ('is_passed', models.BooleanField(default=False, verbose_name='是否通過')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成時間')),
                ('equipment_gained', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EngineerRPG.equipment', verbose_name='獲得裝備')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='EngineerRPG.trial')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_records', to='EngineerRPG.userprofile')),
            ],
            options={
                'verbose_name': '試煉記錄',
                'verbose_name_plural': '試煉記錄',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(verbose_name='當前等級')),
                ('target_level', models.IntegerField(verbose_name='目標等級')),
                ('status', models.CharField(choices=[('PENDING', '待審核'), ('APPROVED', '已通過'), ('REJECTED', '已拒絕')], default='PENDING', max_length=20, verbose_name='審核狀態')),
                ('review_comment', models.TextField(blank=True, verbose_name='審核備註')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_promotions', to=settings.AUTH_USER_MODEL, verbose_name='審核人')),
                ('trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EngineerRPG.trial', verbose_name='升階試煉')),
                ('trial_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EngineerRPG.trialrecord', verbose_name='試煉記錄')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='EngineerRPG.userprofile', verbose_name='申請人')),
            ],
            options={
                'verbose_name': '晉升申請',
                'verbose_name_plural': '晉升申請',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='EnhancementScroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='數量')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='獲得時間')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement_scrolls', to='EngineerRPG.userprofile', verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '強化卷軸',
                'verbose_name_plural': '強化卷軸',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解鎖時間')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.achievement')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='EngineerRPG.userprofile')),
            ],
            options={
                'verbose_name': '使用者成就',
                'verbose_name_plural': '使用者成就',
                'unique_together': {('user_profile', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', '未解鎖'), ('AVAILABLE', '可學習'), ('IN_PROGRESS', '學習中'), ('COMPLETED', '已完成')], default='LOCKED', max_length=20, verbose_name='學習狀態')),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='學習進度(%)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.skillnode')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='EngineerRPG.userprofile')),
            ],
            options={
                'verbose_name': '使用者技能',
                'verbose_name_plural': '使用者技能',
                'unique_together': {('user_profile', 'skill_node')},
            },
        ),
    ]
