# Generated by Django 5.2.9 on 2026-01-06 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='隊伍名稱')),
                ('description', models.TextField(blank=True, verbose_name='隊伍描述')),
                ('project_code', models.CharField(max_length=50, unique=True, verbose_name='計畫代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='隊長')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='EngineerRPG.userprofile', verbose_name='隊員')),
            ],
            options={
                'verbose_name': '隊伍',
                'verbose_name_plural': '隊伍列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
