# Generated by Django 5.2.9 on 2026-01-06 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='team',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='結束日期'),
        ),
        migrations.AddField(
            model_name='team',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='開始日期'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('ACTIVE', '進行中'), ('COMPLETED', '已完工'), ('DISBANDED', '已解散')], default='ACTIVE', max_length=20, verbose_name='狀態'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='EngineerRPG.team', verbose_name='當前隊伍'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='離開時間')),
                ('is_current', models.BooleanField(default=True, verbose_name='當前隊伍')),
                ('leave_reason', models.CharField(blank=True, choices=[('TRANSFER', '轉隊'), ('PROJECT_END', '計畫結束'), ('DISBANDED', '隊伍解散'), ('OTHER', '其他')], max_length=20, null=True, verbose_name='離開原因')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='EngineerRPG.team', verbose_name='隊伍')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_history', to='EngineerRPG.userprofile', verbose_name='隊員')),
            ],
            options={
                'verbose_name': '隊伍成員記錄',
                'verbose_name_plural': '隊伍成員記錄',
                'ordering': ['-joined_at'],
            },
        ),
    ]
