# Generated by Django 5.2.9 on 2026-01-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0003_remove_team_members_team_end_date_team_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADVENTURER', '冒險者'), ('OFFICER', '公會幹部'), ('MANAGER', '公會會長'), ('ADMIN', '創世神')], default='ADVENTURER', max_length=20, verbose_name='角色權限'),
        ),
    ]
