# Generated by Django 5.2.9 on 2026-01-06 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_tool',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_boots', to='EngineerRPG.equipment', verbose_name='靴子'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_1', to='EngineerRPG.equipment', verbose_name='工具1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_2', to='EngineerRPG.equipment', verbose_name='工具2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_3', to='EngineerRPG.equipment', verbose_name='工具3'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_4', to='EngineerRPG.equipment', verbose_name='工具4'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_5', to='EngineerRPG.equipment', verbose_name='工具5'),
        ),
    ]
