# Generated by Django 5.2.9 on 2026-01-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0005_remove_userprofile_equipped_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialrecord',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.trial'),
        ),
        migrations.CreateModel(
            name='DailyTrialTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('task_number', models.IntegerField(choices=[(1, '任務一'), (2, '任務二'), (3, '任務三')], verbose_name='任務編號')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('questions', models.ManyToManyField(to='EngineerRPG.question', verbose_name='題目')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.trial', verbose_name='試煉')),
            ],
            options={
                'verbose_name': '每日試煉任務',
                'verbose_name_plural': '每日試煉任務',
                'ordering': ['date', 'task_number'],
                'unique_together': {('date', 'task_number')},
            },
        ),
        migrations.AddField(
            model_name='trialrecord',
            name='daily_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='EngineerRPG.dailytrialtask', verbose_name='每日任務'),
        ),
        migrations.CreateModel(
            name='DailyTrialProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField(verbose_name='當前 HP')),
                ('current_mp', models.IntegerField(verbose_name='當前 MP')),
                ('initial_hp', models.IntegerField(verbose_name='初始 HP')),
                ('initial_mp', models.IntegerField(verbose_name='初始 MP')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('is_passed', models.BooleanField(default=False, verbose_name='通過')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='答題記錄')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_trial_progress', to='EngineerRPG.userprofile', verbose_name='使用者')),
                ('daily_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='EngineerRPG.dailytrialtask', verbose_name='每日任務')),
            ],
            options={
                'verbose_name': '每日試煉進度',
                'verbose_name_plural': '每日試煉進度',
                'unique_together': {('user_profile', 'daily_task')},
            },
        ),
    ]
