# Generated by Django 5.2.9 on 2026-01-07 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0006_alter_trialrecord_trial_dailytrialtask_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('category', models.CharField(choices=[('GENERAL', '綜合討論'), ('STRATEGY', '攻略心得'), ('TEAM', '組隊招募'), ('QA', '問題請教'), ('ANNOUNCEMENT', '公會公告')], default='GENERAL', max_length=20, verbose_name='分類')),
                ('views', models.IntegerField(default=0, verbose_name='瀏覽數')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置頂')),
                ('is_locked', models.BooleanField(default=False, verbose_name='鎖定')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_posts', to='EngineerRPG.userprofile', verbose_name='發布者')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='EngineerRPG.userprofile', verbose_name='按讚')),
            ],
            options={
                'verbose_name': '公會貼文',
                'verbose_name_plural': '公會貼文',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuildComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='留言時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_comments', to='EngineerRPG.userprofile', verbose_name='留言者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='EngineerRPG.guildpost', verbose_name='貼文')),
            ],
            options={
                'verbose_name': '公會留言',
                'verbose_name_plural': '公會留言',
                'ordering': ['created_at'],
            },
        ),
    ]
