# Generated by Django 5.2.9 on 2026-01-09 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0007_guildpost_guildcomment'),
    ]

    operations = [
        # 重命名舊欄位（保留資料）
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_helmet',
            new_name='equipped_helmet_old',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_armor',
            new_name='equipped_armor_old',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_boots',
            new_name='equipped_boots_old',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_tool_1',
            new_name='equipped_tool_1_old',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_tool_2',
            new_name='equipped_tool_2_old',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_tool_3',
            new_name='equipped_tool_3_old',
        ),
        # 刪除 tool_4 和 tool_5（不需要了）
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_tool_4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_tool_5',
        ),
        # 添加強化券欄位
        migrations.AddField(
            model_name='userprofile',
            name='enhancement_tickets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='強化券數量'),
        ),
        # 添加新裝備欄位（指向 UserEquipment）
        migrations.AddField(
            model_name='userprofile',
            name='equipped_helmet_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_helmet', to='EngineerRPG.userequipment', verbose_name='頭盔'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_armor_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_armor', to='EngineerRPG.userequipment', verbose_name='護甲'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_boots_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_boots', to='EngineerRPG.userequipment', verbose_name='靴子'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_1_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_1', to='EngineerRPG.userequipment', verbose_name='工具1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_2_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_2', to='EngineerRPG.userequipment', verbose_name='工具2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_3_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_3', to='EngineerRPG.userequipment', verbose_name='工具3'),
        ),
        # 更新 UserEquipment
        migrations.AlterField(
            model_name='userequipment',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_equipment', to='EngineerRPG.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='userequipment',
            unique_together={('user_profile', 'equipment')},
        ),
    ]
