# Generated by manual creation for equipment data migration

from django.db import migrations


def migrate_equipped_items(apps, schema_editor):
    """將舊的裝備槽位資料遷移到新系統"""
    UserProfile = apps.get_model('EngineerRPG', 'UserProfile')
    UserEquipment = apps.get_model('EngineerRPG', 'UserEquipment')
    Equipment = apps.get_model('EngineerRPG', 'Equipment')
    
    migrated_count = 0
    created_user_equipment_count = 0
    
    for profile in UserProfile.objects.all():
        # 處理每個裝備槽位
        slots = [
            ('equipped_helmet_old', 'equipped_helmet_new'),
            ('equipped_armor_old', 'equipped_armor_new'),
            ('equipped_boots_old', 'equipped_boots_new'),
            ('equipped_tool_1_old', 'equipped_tool_1_new'),
            ('equipped_tool_2_old', 'equipped_tool_2_new'),
            ('equipped_tool_3_old', 'equipped_tool_3_new'),
        ]
        
        for old_field, new_field in slots:
            old_equipment = getattr(profile, old_field, None)
            
            if old_equipment:
                # 為這個裝備創建或獲取 UserEquipment 實例
                user_eq, created = UserEquipment.objects.get_or_create(
                    user_profile=profile,
                    equipment=old_equipment,
                    defaults={'enhancement_level': 0}
                )
                
                if created:
                    created_user_equipment_count += 1
                
                # 將 UserEquipment 設置到新欄位
                setattr(profile, new_field, user_eq)
                migrated_count += 1
        
        # 保存更新
        if migrated_count > 0:
            profile.save()
    
    print(f"✅ 遷移完成：")
    print(f"   - 遷移了 {migrated_count} 個裝備槽位")
    print(f"   - 創建了 {created_user_equipment_count} 個 UserEquipment 實例")


def reverse_migration(apps, schema_editor):
    """回滾遷移：將新欄位的資料還原到舊欄位"""
    UserProfile = apps.get_model('EngineerRPG', 'UserProfile')
    
    for profile in UserProfile.objects.all():
        slots = [
            ('equipped_helmet_new', 'equipped_helmet_old'),
            ('equipped_armor_new', 'equipped_armor_old'),
            ('equipped_boots_new', 'equipped_boots_old'),
            ('equipped_tool_1_new', 'equipped_tool_1_old'),
            ('equipped_tool_2_new', 'equipped_tool_2_old'),
            ('equipped_tool_3_new', 'equipped_tool_3_old'),
        ]
        
        for new_field, old_field in slots:
            user_equipment = getattr(profile, new_field, None)
            
            if user_equipment:
                # 將 UserEquipment 的 Equipment 還原到舊欄位
                setattr(profile, old_field, user_equipment.equipment)
                # 清空新欄位
                setattr(profile, new_field, None)
        
        profile.save()
    
    print("✅ 回滾完成")


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0008_equipment_refactor_phase1'),
    ]

    operations = [
        migrations.RunPython(migrate_equipped_items, reverse_migration),
    ]
