# Generated by Django 5.2.9 on 2026-01-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0009_migrate_equipment_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_armor_new',
            new_name='equipped_armor',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_boots_new',
            new_name='equipped_boots',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_helmet_new',
            new_name='equipped_helmet',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_tool_1_new',
            new_name='equipped_tool_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_tool_2_new',
            new_name='equipped_tool_2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='equipped_tool_3_new',
            new_name='equipped_tool_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_armor_old',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_boots_old',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_helmet_old',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_tool_1_old',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_tool_2_old',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='equipped_tool_3_old',
        ),
    ]
