# Generated by Django 5.2.9 on 2026-01-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0010_equipment_refactor_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_index',
            field=models.IntegerField(default=0, help_text='0表示使用上傳頭像或隨機，1-20表示選擇的預設頭像', verbose_name='預設頭像索引'),
        ),
    ]
