# Generated by Django 5.2.9 on 2026-01-11 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0011_userprofile_avatar_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillnode',
            name='min_level',
            field=models.IntegerField(default=1, help_text='學習此技能所需的最低角色等級', validators=[django.core.validators.MinValueValidator(1)], verbose_name='最低等級需求'),
        ),
    ]
