# Generated by Django 5.2.9 on 2026-01-11 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0012_skillnode_min_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, verbose_name='分類描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rpg/categories/', verbose_name='分類圖示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '題目分類',
                'verbose_name_plural': '題目分類',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='trial',
            name='trial_type',
            field=models.CharField(choices=[('DAILY', '每日副本'), ('DUNGEON', '地下城'), ('PROMOTION', '升階試煉'), ('SPECIAL', '特殊活動')], max_length=20, verbose_name='試煉類型'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='EngineerRPG.questioncategory', verbose_name='題目分類'),
        ),
        migrations.AddField(
            model_name='trial',
            name='category',
            field=models.ForeignKey(blank=True, help_text='僅地下城類型需要設定此欄位', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dungeons', to='EngineerRPG.questioncategory', verbose_name='所屬分類'),
        ),
    ]
