# Generated by Django 5.2.9 on 2026-01-11 15:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0013_questioncategory_alter_trial_trial_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='道具名稱')),
                ('description', models.TextField(verbose_name='道具描述')),
                ('item_type', models.CharField(choices=[('BASIC', '基礎道具'), ('ADVANCED', '進階道具'), ('RARE', '稀有道具')], default='BASIC', max_length=20, verbose_name='道具類型')),
                ('rarity', models.CharField(choices=[('COMMON', '普通 (Common)'), ('RARE', '稀有 (Rare)'), ('EPIC', '史詩 (Epic)'), ('LEGENDARY', '傳說 (Legendary)')], default='COMMON', max_length=20, verbose_name='稀有度')),
                ('effect_type', models.CharField(choices=[('HINT', '提示 (Show Hint)'), ('HEAL', '回復 HP (Heal HP)'), ('REMOVE_OPTION', '刪除選項 (Remove Option)'), ('SHIELD', '抵擋傷害 (Shield)'), ('TIME_EXTEND', '延長時間 (Extend Time)'), ('DISTRIBUTION', '機率分佈 (Show Distribution)'), ('SKIP', '跳題 (Skip Question)'), ('COMBO_PROTECT', '連勝保護 (Combo Protect)')], max_length=20, verbose_name='效果類型')),
                ('effect_value', models.IntegerField(default=0, help_text='例如：回復10% HP則填10，延長30秒則填30', verbose_name='效果數值')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='rpg/item_icons/', verbose_name='道具圖示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具列表',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_4', to='EngineerRPG.userequipment', verbose_name='工具欄4'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='equipped_tool_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_5', to='EngineerRPG.userequipment', verbose_name='工具欄5'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.CharField(choices=[('HELMET', '頭盔 (Helmet)'), ('ARMOR', '盔甲 (Armor)'), ('BOOTS', '靴子 (Boots)'), ('TOOL', '工具 (Tool)')], max_length=20, verbose_name='裝備類型'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='mp_cost',
            field=models.IntegerField(default=0, verbose_name='MP消耗'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rarity',
            field=models.CharField(choices=[('COMMON', '普通 (Common)'), ('RARE', '稀有 (Rare)'), ('EPIC', '史詩 (Epic)'), ('LEGENDARY', '傳說 (Legendary)')], default='COMMON', max_length=20, verbose_name='稀有度'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='required_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EngineerRPG.skillnode', verbose_name='需求技能'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='skill_description',
            field=models.TextField(blank=True, null=True, verbose_name='技能描述'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='skill_effect',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='技能效果'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_armor', to='EngineerRPG.userequipment', verbose_name='裝備盔甲'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_boots', to='EngineerRPG.userequipment', verbose_name='裝備靴子'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_helmet', to='EngineerRPG.userequipment', verbose_name='裝備頭盔'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_tool_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_1', to='EngineerRPG.userequipment', verbose_name='工具欄1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_tool_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_2', to='EngineerRPG.userequipment', verbose_name='工具欄2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='equipped_tool_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_as_tool_3', to='EngineerRPG.userequipment', verbose_name='工具欄3'),
        ),
        migrations.AddField(
            model_name='trial',
            name='item_reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_item_rewards', to='EngineerRPG.item', verbose_name='道具獎勵'),
        ),
        migrations.AddField(
            model_name='trialrecord',
            name='item_gained',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EngineerRPG.item', verbose_name='獲得道具'),
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='數量')),
                ('obtained_at', models.DateTimeField(auto_now_add=True, verbose_name='獲得時間')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.item')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='EngineerRPG.userprofile')),
            ],
            options={
                'verbose_name': '使用者道具',
                'verbose_name_plural': '使用者道具',
                'unique_together': {('user_profile', 'item')},
            },
        ),
    ]
