# Generated by Django 5.2.9 on 2026-01-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0014_item_userprofile_equipped_tool_4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'managed': False, 'verbose_name': '隊伍', 'verbose_name_plural': '隊伍列表'},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'managed': False, 'verbose_name': '隊伍成員', 'verbose_name_plural': '隊伍成員列表'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='damage_reduction',
            field=models.IntegerField(default=0, help_text='正值表示減傷，例如 2 表示減傷 2 點', verbose_name='減傷值 (DR)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='enhancement_rules',
            field=models.JSONField(blank=True, default=dict, help_text='定義各強化等級的詳細數值', verbose_name='強化規則'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='special_ability_description',
            field=models.TextField(blank=True, null=True, verbose_name='+9 特殊能力描述'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='special_ability_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='+9 特殊能力名稱'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=1, verbose_name='階級'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='max_enhancement',
            field=models.IntegerField(default=9, verbose_name='最大強化等級'),
        ),
        migrations.AlterField(
            model_name='guildpost',
            name='category',
            field=models.CharField(choices=[('GENERAL', '綜合討論'), ('STRATEGY', '攻略心得'), ('QA', '問題請教'), ('ANNOUNCEMENT', '公會公告')], default='GENERAL', max_length=20, verbose_name='分類'),
        ),
    ]
