# Generated by Django 5.2.9 on 2026-01-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0015_alter_team_options_alter_teammembership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='EngineerRPG.team', verbose_name='當前隊伍'),
        ),
        migrations.AlterModelTable(
            name='team',
            table='TeamKnowledgeHub_knowledgeteam',
        ),
        migrations.AlterModelTable(
            name='teammembership',
            table='TeamKnowledgeHub_knowledgeteammember',
        ),
    ]
