# Generated by Django 5.2.9 on 2026-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0016_alter_userprofile_current_team_alter_team_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrialprogress',
            name='current_question_index',
            field=models.IntegerField(default=0, verbose_name='當前題目索引'),
        ),
    ]
