# Generated by Django 5.2.9 on 2026-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0017_dailytrialprogress_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_time_limit',
            field=models.IntegerField(default=20, verbose_name='考試時限（分鐘）'),
        ),
        migrations.AddField(
            model_name='course',
            name='exp_reward',
            field=models.IntegerField(default=100, verbose_name='經驗獎勵'),
        ),
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=60, verbose_name='及格分數'),
        ),
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='courses', to='EngineerRPG.question', verbose_name='考試題目'),
        ),
    ]
