# Generated by Django 5.2.9 on 2026-02-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0018_course_exam_time_limit_course_exp_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exp_reward',
        ),
    ]
