# Generated by Django 5.2.9 on 2026-02-01 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0019_remove_course_exp_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content_type',
            field=models.CharField(choices=[('PDF', 'PDF文件'), ('LINK', '外部連結')], max_length=10, verbose_name='內容類型'),
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('score', models.IntegerField(default=0, verbose_name='最高分數')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='EngineerRPG.course')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='EngineerRPG.userprofile')),
            ],
            options={
                'verbose_name': '使用者課程進度',
                'verbose_name_plural': '使用者課程進度',
                'unique_together': {('user_profile', 'course')},
            },
        ),
    ]
