# Generated by Django 5.2.9 on 2026-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0020_alter_course_content_type_usercourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('INTERN', '實習生'), ('ASSISTANT', '助理工程師'), ('ENGINEER', '工程師')], default='INTERN', max_length=20, verbose_name='職銜'),
        ),
        migrations.AlterField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=80, verbose_name='及格分數'),
        ),
    ]
