# Generated by Django 5.2.10 on 2026-02-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0021_userprofile_rank_alter_course_passing_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='對應 User.username', max_length=150, unique=True, verbose_name='使用者帳號')),
                ('role', models.CharField(choices=[('OFFICER', '公會幹部'), ('MANAGER', '公會會長')], max_length=20, verbose_name='授予角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '管理員白名單',
                'verbose_name_plural': '管理員白名單',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='請輸入 static 資料夾下的相對路徑', max_length=255, verbose_name='裝備圖示路徑'),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='請輸入 static 資料夾下的相對路徑', max_length=255, verbose_name='道具圖示路徑'),
        ),
    ]
