# Generated by Django 5.2.9 on 2026-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0021_userprofile_rank_alter_course_passing_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='icon',
            field=models.CharField(blank=True, help_text='Static 路徑，例如: EngineerRPG/img/equipment_icons/helmet.png', max_length=200, null=True, verbose_name='裝備圖示路徑'),
        ),
    ]
