# Generated by Django 5.2.10 on 2026-02-04 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0022_change_icon_to_charfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADVENTURER', '冒險者'), ('OFFICER', '公會幹部'), ('MANAGER', '公會會長'), ('ADMIN', '創世神')], default='OFFICER', help_text='為此使用者指定的管理角色', max_length=20, verbose_name='指定角色')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授權時間')),
                ('notes', models.TextField(blank=True, help_text='授權原因或其他說明', verbose_name='備註')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_admin_rights', to=settings.AUTH_USER_MODEL, verbose_name='授權者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_whitelist', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '管理者白名單',
                'verbose_name_plural': '管理者白名單',
                'ordering': ['-granted_at'],
            },
        ),
    ]
