# Generated by Django 5.2.9 on 2026-02-11 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0022_adminwhitelist_alter_equipment_icon_alter_item_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='EngineerRPG.characterclass', verbose_name='職業'),
        ),
    ]
