# Generated by Django 5.2.10 on 2026-02-04 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0023_adminwhitelist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user_profile',
        ),
        migrations.CreateModel(
            name='RPGTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='團隊名稱')),
                ('description', models.TextField(blank=True, verbose_name='團隊說明')),
                ('max_members', models.IntegerField(default=6, verbose_name='最大成員數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rpg_teams', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_rpg_teams', to=settings.AUTH_USER_MODEL, verbose_name='隊長')),
            ],
            options={
                'verbose_name': 'RPG團隊',
                'verbose_name_plural': 'RPG團隊列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RPGTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', '隊長'), ('VICE_LEADER', '副隊長'), ('MEMBER', '成員')], default='MEMBER', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='EngineerRPG.rpgteam', verbose_name='團隊')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpg_team_memberships', to='EngineerRPG.userprofile', verbose_name='成員')),
            ],
            options={
                'verbose_name': 'RPG團隊成員',
                'verbose_name_plural': 'RPG團隊成員列表',
                'ordering': ['joined_at'],
                'unique_together': {('team', 'user_profile')},
            },
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
    ]
