# Generated by Django 5.2.10 on 2026-02-12 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0023_alter_userprofile_character_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Create the new independent RPG Team table
        migrations.CreateModel(
            name='RPGTeamTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='隊伍名稱')),
                ('description', models.TextField(blank=True, verbose_name='隊伍說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='rpg_led_teams_temp', to=settings.AUTH_USER_MODEL, verbose_name='隊長')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='rpg_created_teams_temp', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'db_table': 'EngineerRPG_rpgteam',
                'verbose_name': '隊伍',
                'verbose_name_plural': '隊伍列表',
            },
        ),

        # Step 2: Create the new independent RPG TeamMembership table
        migrations.CreateModel(
            name='RPGTeamMembershipTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EngineerRPG.rpgteamtemp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EngineerRPG_rpgteammembership',
                'verbose_name': '隊伍成員',
                'verbose_name_plural': '隊伍成員列表',
                'unique_together': {('team', 'user')},
            },
        ),

        # Step 3: Delete old unmanaged models
        migrations.DeleteModel(
            name='TeamMembership',
        ),
        migrations.DeleteModel(
            name='Team',
        ),

        # Step 4: Rename the temp models to the final names
        migrations.RenameModel(
            old_name='RPGTeamTemp',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='RPGTeamMembershipTemp',
            new_name='TeamMembership',
        ),

        # Step 5: Fix the related_names after rename
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='隊長'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),

        # Step 6: Update UserProfile.current_team FK to point properly  
        migrations.AlterField(
            model_name='userprofile',
            name='current_team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                   on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='current_members', to='EngineerRPG.team',
                                   verbose_name='當前隊伍'),
        ),
    ]
