# Generated by Django 5.2.11 on 2026-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0024_rpgteam_independent_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emp_dept',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='所屬部門'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
