# Generated by Django 5.2.10 on 2026-02-04 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0024_remove_userprofile_current_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_obtainable',
            field=models.BooleanField(default=True, help_text='此裝備目前是否可以被獲得', verbose_name='可獲得'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='obtain_description',
            field=models.TextField(blank=True, help_text='詳細說明如何獲得此裝備，例如：通過職安地下城第3層可獲得', verbose_name='獲取說明'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='obtain_method',
            field=models.CharField(choices=[('TRIAL', '試煉獎勵'), ('DUNGEON', '地下城掉落'), ('DAILY', '每日任務'), ('ACHIEVEMENT', '成就獎勵'), ('SKILL', '技能解鎖'), ('PROMOTION', '晉升獎勵'), ('SPECIAL', '特殊活動'), ('STARTER', '初始裝備')], default='TRIAL', help_text='此裝備的主要獲取途徑', max_length=20, verbose_name='主要獲取方式'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='obtain_trial',
            field=models.ForeignKey(blank=True, help_text='可從哪個試煉獲得此裝備', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='droppable_equipment', to='EngineerRPG.trial', verbose_name='關聯試煉'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_obtainable',
            field=models.BooleanField(default=True, help_text='此道具目前是否可以被獲得', verbose_name='可獲得'),
        ),
        migrations.AddField(
            model_name='item',
            name='obtain_description',
            field=models.TextField(blank=True, help_text='詳細說明如何獲得此道具', verbose_name='獲取說明'),
        ),
        migrations.AddField(
            model_name='item',
            name='obtain_method',
            field=models.CharField(choices=[('TRIAL', '試煉獎勵'), ('DUNGEON', '地下城掉落'), ('DAILY', '每日任務'), ('ACHIEVEMENT', '成就獎勵'), ('COMBO', '連勝獎勵'), ('SPECIAL', '特殊活動'), ('STARTER', '初始道具')], default='TRIAL', help_text='此道具的主要獲取途徑', max_length=20, verbose_name='主要獲取方式'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_class_selected',
            field=models.BooleanField(default=False, verbose_name='已選擇職業'),
        ),
    ]
