# Generated by Django 5.2.11 on 2026-02-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0025_team_emp_dept_alter_team_id_alter_teammembership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrialprogress',
            name='boots_correct_streak',
            field=models.IntegerField(default=0, help_text='用於追蹤連續答對,答錯時重置', verbose_name='連續答對次數'),
        ),
        migrations.AddField(
            model_name='dailytrialprogress',
            name='boots_total_correct',
            field=models.IntegerField(default=0, help_text='用於追蹤累積答對,不會重置', verbose_name='累積答對次數'),
        ),
    ]
