# Generated by Django 5.2.11 on 2026-02-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0026_dailytrialprogress_boots_correct_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytrialprogress',
            name='chest_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='寶箱資料'),
        ),
    ]
