# Generated by Django 5.2.11 on 2026-02-25 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0027_dailytrialprogress_chest_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '部門', 'verbose_name_plural': '部門列表'},
        ),
        migrations.AlterModelOptions(
            name='teammembership',
            options={'verbose_name': '部門成員', 'verbose_name_plural': '部門成員列表'},
        ),
        migrations.AlterField(
            model_name='adminwhitelist',
            name='role',
            field=models.CharField(choices=[('OFFICER', '幹部'), ('MANAGER', '董事長')], max_length=20, verbose_name='授予角色'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='部門說明'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='部門主管'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, verbose_name='部門名稱'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', '成員'), ('LEADER', '部門主管'), ('VICE_LEADER', '部門副主管')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADVENTURER', '冒險者'), ('OFFICER', '幹部'), ('MANAGER', '董事長')], default='ADVENTURER', max_length=20, verbose_name='角色權限'),
        ),
    ]
