# Generated by Django 5.1.2 on 2026-02-25 10:46

from django.db import migrations


def downgrade_admins_to_officer(apps, schema_editor):
    UserProfile = apps.get_model('EngineerRPG', 'UserProfile')
    AdminWhitelist = apps.get_model('EngineerRPG', 'AdminWhitelist')

    UserProfile.objects.filter(role='ADMIN').update(role='OFFICER')
    AdminWhitelist.objects.filter(role='ADMIN').update(role='OFFICER')


def revert_officer_to_admin(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0028_alter_team_options_alter_teammembership_options_and_more'),
    ]

    operations = [
        migrations.RunPython(downgrade_admins_to_officer, revert_officer_to_admin),
    ]
