# Generated by Django 5.2.11 on 2026-03-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EngineerRPG', '0029_auto_20260225_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '隊伍', 'verbose_name_plural': '隊伍列表'},
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='adminwhitelist',
            name='role',
            field=models.CharField(choices=[('OFFICER', '公會幹部'), ('MANAGER', '公會會長')], max_length=20, verbose_name='授予角色'),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', '成員'), ('LEADER', '隊長'), ('VICE_LEADER', '副隊長')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADVENTURER', '冒險者'), ('OFFICER', '公會幹部'), ('MANAGER', '公會會長')], default='ADVENTURER', max_length=20, verbose_name='角色權限'),
        ),
    ]
