# Generated by Django 5.2.9 on 2025-12-22 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='團隊名稱')),
                ('description', models.TextField(blank=True, verbose_name='團隊說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dev_teams', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '開發團隊',
                'verbose_name_plural': '開發團隊',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='程式名稱')),
                ('program_type', models.CharField(choices=[('web', '網頁'), ('desktop', '單機程式'), ('plugin', '外掛程式')], max_length=20, verbose_name='程式類型')),
                ('english_name', models.CharField(blank=True, max_length=200, verbose_name='英文名稱')),
                ('url', models.URLField(blank=True, verbose_name='網址')),
                ('dev_tool', models.CharField(max_length=200, verbose_name='開發工具')),
                ('git_url', models.URLField(blank=True, verbose_name='Git 網址')),
                ('last_modified', models.DateTimeField(verbose_name='最後變更時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='ProgramDbRegistry.devteam', verbose_name='所屬團隊')),
            ],
            options={
                'verbose_name': '程式',
                'verbose_name_plural': '程式',
                'ordering': ['-last_modified', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='檔案路徑')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_locations', to='ProgramDbRegistry.program', verbose_name='程式')),
            ],
            options={
                'verbose_name': '存取檔案位置',
                'verbose_name_plural': '存取檔案位置',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=200, verbose_name='資料庫伺服器')),
                ('database_name', models.CharField(max_length=200, verbose_name='資料庫名稱')),
                ('table_name', models.CharField(max_length=200, verbose_name='資料表')),
                ('access_permission', models.CharField(choices=[('readonly', '唯讀'), ('readwrite', '可寫入')], max_length=20, verbose_name='存取權限')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='ProgramDbRegistry.program', verbose_name='程式')),
            ],
            options={
                'verbose_name': '使用資料庫',
                'verbose_name_plural': '使用資料庫',
                'ordering': ['database_name', 'table_name'],
            },
        ),
        migrations.CreateModel(
            name='DevTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', '建立者'), ('member', '成員')], default='member', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ProgramDbRegistry.devteam', verbose_name='團隊')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '團隊成員',
                'verbose_name_plural': '團隊成員',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintained_programs', to=settings.AUTH_USER_MODEL, verbose_name='維運者')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintainers', to='ProgramDbRegistry.program', verbose_name='程式')),
            ],
            options={
                'verbose_name': '維運者',
                'verbose_name_plural': '維運者',
                'unique_together': {('program', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developed_programs', to=settings.AUTH_USER_MODEL, verbose_name='開發者')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='ProgramDbRegistry.program', verbose_name='程式')),
            ],
            options={
                'verbose_name': '開發者',
                'verbose_name_plural': '開發者',
                'unique_together': {('program', 'user')},
            },
        ),
    ]
