# Generated by Django 5.2.9 on 2025-12-22 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramDbRegistry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseDesignDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='文件名稱')),
                ('doc_type', models.CharField(choices=[('manual', '手動建立'), ('django', 'Django Model'), ('mermaid', 'Mermaid 圖表')], max_length=20, verbose_name='文件類型')),
                ('django_model_code', models.TextField(blank=True, help_text='貼上 Django Model 程式碼，系統將自動解析', verbose_name='Django Model 程式碼')),
                ('mermaid_content', models.TextField(blank=True, help_text='自動生成的 Mermaid ER Diagram 內容', verbose_name='Mermaid 內容')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_docs', to='ProgramDbRegistry.program', verbose_name='程式')),
            ],
            options={
                'verbose_name': '資料庫設計文件',
                'verbose_name_plural': '資料庫設計文件',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200, verbose_name='資料表名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('design_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='ProgramDbRegistry.databasedesigndoc', verbose_name='設計文件')),
            ],
            options={
                'verbose_name': '設計資料表',
                'verbose_name_plural': '設計資料表',
                'ordering': ['order', 'table_name'],
                'unique_together': {('design_doc', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='DesignField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, verbose_name='欄位名稱')),
                ('data_type', models.CharField(choices=[('INTEGER', 'INTEGER'), ('BIGINT', 'BIGINT'), ('SMALLINT', 'SMALLINT'), ('VARCHAR', 'VARCHAR'), ('TEXT', 'TEXT'), ('BOOLEAN', 'BOOLEAN'), ('DATE', 'DATE'), ('DATETIME', 'DATETIME'), ('TIME', 'TIME'), ('FLOAT', 'FLOAT'), ('DECIMAL', 'DECIMAL'), ('UUID', 'UUID'), ('BLOB', 'BLOB'), ('JSON', 'JSON'), ('FK', 'FOREIGN KEY'), ('M2M', 'MANY TO MANY')], max_length=50, verbose_name='資料類型')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('is_primary_key', models.BooleanField(default=False, verbose_name='是否為主鍵')),
                ('is_foreign_key', models.BooleanField(default=False, verbose_name='是否為外鍵')),
                ('fk_reference_table', models.CharField(blank=True, help_text='如果是外鍵，填入參考的資料表名稱', max_length=200, verbose_name='外鍵參考表')),
                ('is_nullable', models.BooleanField(default=True, verbose_name='可否為空')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='預設值')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ProgramDbRegistry.designtable', verbose_name='資料表')),
            ],
            options={
                'verbose_name': '設計欄位',
                'verbose_name_plural': '設計欄位',
                'ordering': ['order', 'field_name'],
            },
        ),
    ]
