# Generated by Django 5.2.9 on 2025-12-22 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramDbRegistry', '0002_databasedesigndoc_designtable_designfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='伺服器名稱')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '資料庫伺服器',
                'verbose_name_plural': '資料庫伺服器',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='maintainer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maintainer',
            name='program',
        ),
        migrations.RemoveField(
            model_name='maintainer',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='programdatabase',
            options={'ordering': ['server__name', 'database_name', 'table_name'], 'verbose_name': '使用資料庫', 'verbose_name_plural': '使用資料庫'},
        ),
        migrations.RemoveField(
            model_name='program',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='program',
            name='developers',
            field=models.CharField(blank=True, help_text='多位請用逗號分隔', max_length=200, verbose_name='開發者'),
        ),
        migrations.AddField(
            model_name='program',
            name='maintainers',
            field=models.CharField(blank=True, help_text='多位請用逗號分隔', max_length=200, verbose_name='維運者'),
        ),
        migrations.AlterField(
            model_name='program',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='最後變更時間'),
        ),
        migrations.AlterField(
            model_name='programdatabase',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='databases', to='ProgramDbRegistry.databaseserver', verbose_name='資料庫伺服器'),
        ),
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='Maintainer',
        ),
    ]
