# Generated by Django 5.2.9 on 2025-12-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramDbRegistry', '0003_databaseserver_alter_maintainer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='git_url',
            field=models.URLField(verbose_name='Git 網址'),
        ),
    ]
