# Generated by Django 5.2.9 on 2025-12-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramDbRegistry', '0004_alter_program_git_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasedesigndoc',
            name='doc_type',
            field=models.CharField(choices=[('manual', '手動建立'), ('django', 'Django Model')], max_length=20, verbose_name='文件類型'),
        ),
    ]
