# Generated by Django 5.2.9 on 2025-12-31 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramDbRegistry', '0006_alter_databasedesigndoc_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='平台名稱')),
                ('api_endpoint', models.URLField(blank=True, verbose_name='API 端點')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('auth_type', models.CharField(choices=[('none', '無需驗證'), ('api_key', 'API Key'), ('oauth', 'OAuth'), ('token', 'Token'), ('basic', 'Basic Auth')], default='none', max_length=20, verbose_name='驗證方式')),
                ('documentation_url', models.URLField(blank=True, verbose_name='文件連結')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '平台 API',
                'verbose_name_plural': '平台 API',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_path', models.CharField(blank=True, help_text='例如：/api/v1/users', max_length=500, verbose_name='API 路徑')),
                ('access_type', models.CharField(choices=[('consume', '呼叫使用'), ('provide', '提供服務')], default='consume', max_length=20, verbose_name='存取類型')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='說明')),
                ('platform_api', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='ProgramDbRegistry.platformapi', verbose_name='平台 API')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usages', to='ProgramDbRegistry.program', verbose_name='程式')),
            ],
            options={
                'verbose_name': '使用平台 API',
                'verbose_name_plural': '使用平台 API',
                'ordering': ['platform_api__name', 'api_path'],
            },
        ),
    ]
