# Generated by Django 5.2.9 on 2025-12-31 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgramDbRegistry', '0007_platformapi_programapiusage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('data_sync', '資料同步'), ('report', '報表產生'), ('notification', '通知發送'), ('backup', '備份作業'), ('cleanup', '清理作業'), ('monitoring', '監控檢查'), ('other', '其他')], max_length=50, verbose_name='分類')),
                ('code', models.CharField(max_length=50, verbose_name='編號')),
                ('name', models.CharField(max_length=200, verbose_name='名稱')),
                ('device', models.CharField(max_length=200, verbose_name='排程設備')),
                ('frequency', models.CharField(choices=[('hourly', '每小時'), ('daily', '每日'), ('weekly', '每週'), ('monthly', '每月'), ('custom', '自訂')], max_length=20, verbose_name='頻率')),
                ('frequency_note', models.CharField(blank=True, help_text='例如：每天晚上3點', max_length=200, verbose_name='頻率備註')),
                ('purpose', models.TextField(verbose_name='作用')),
                ('status', models.CharField(choices=[('active', '運作中'), ('retired', '已退休')], default='active', max_length=20, verbose_name='狀態')),
                ('retirement_reason', models.TextField(blank=True, verbose_name='退休原因')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='退休時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_virtual_employees', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_employees', to='ProgramDbRegistry.devteam', verbose_name='所屬團隊')),
            ],
            options={
                'verbose_name': '虛擬員工',
                'verbose_name_plural': '虛擬員工',
                'ordering': ['status', 'category', 'code'],
                'unique_together': {('team', 'code')},
            },
        ),
    ]
