# Generated by Django 5.2.9 on 2026-01-02 05:37

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_knowledge_items', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '知識項目',
                'verbose_name_plural': '知識項目',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TeamKnowledgeHub.knowledgeitem', verbose_name='所屬項目')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='團隊名稱')),
                ('description', models.TextField(blank=True, verbose_name='團隊說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_knowledge_teams', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '知識團隊',
                'verbose_name_plural': '知識團隊',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='主題名稱')),
                ('description', models.TextField(blank=True, verbose_name='主題說明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='TeamKnowledgeHub.knowledgeteam', verbose_name='所屬團隊')),
            ],
            options={
                'verbose_name': '主題',
                'verbose_name_plural': '主題',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TeamKnowledgeHub.topic', verbose_name='所屬主題'),
        ),
        migrations.CreateModel(
            name='KnowledgeTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', '建立者'), ('member', '成員')], default='member', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='TeamKnowledgeHub.knowledgeteam', verbose_name='團隊')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '團隊成員',
                'verbose_name_plural': '團隊成員',
                'ordering': ['role', 'joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
