# Generated by Django 5.2.9 on 2026-01-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamKnowledgeHub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分類名稱')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='TeamKnowledgeHub.topic', verbose_name='所屬主題')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='knowledgeitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='TeamKnowledgeHub.category', verbose_name='所屬分類'),
        ),
    ]
