# Generated by Django 5.2.9 on 2026-01-07 12:19

import TeamKnowledgeHub.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamKnowledgeHub', '0002_category_knowledgeitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=TeamKnowledgeHub.models.comment_attachment_path, verbose_name='檔案')),
                ('filename', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='檔案大小(bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='TeamKnowledgeHub.itemcomment', verbose_name='所屬留言')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_comment_attachments', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_comment_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '留言附件',
                'verbose_name_plural': '留言附件',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=TeamKnowledgeHub.models.item_attachment_path, verbose_name='檔案')),
                ('filename', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='檔案大小(bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_item_attachments', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='TeamKnowledgeHub.knowledgeitem', verbose_name='所屬項目')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_item_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上傳者')),
            ],
            options={
                'verbose_name': '項目附件',
                'verbose_name_plural': '項目附件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
