# Generated by Django 5.2.9 on 2026-01-08 01:17

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeamKnowledgeHub', '0003_commentattachment_itemattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='標題')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_archived', models.BooleanField(default=False, verbose_name='已歸檔')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_notes', to=settings.AUTH_USER_MODEL, verbose_name='擁有者')),
            ],
            options={
                'verbose_name': '快速筆記',
                'verbose_name_plural': '快速筆記',
                'ordering': ['-updated_at'],
            },
        ),
    ]
