# Generated by Django 5.2.9 on 2026-01-08 06:41

import SinoFile.fields
import TeamKnowledgeHub.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeamKnowledgeHub', '0004_quicknote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=SinoFile.fields.SinoFileField(upload_to=TeamKnowledgeHub.models.comment_attachment_path, verbose_name='檔案'),
        ),
        migrations.AlterField(
            model_name='itemattachment',
            name='file',
            field=SinoFile.fields.SinoFileField(upload_to=TeamKnowledgeHub.models.item_attachment_path, verbose_name='檔案'),
        ),
    ]
