# Generated by Django 5.2.10 on 2026-01-27 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='模型名稱')),
                ('file', models.FileField(upload_to='sinoVR/assets/3d/', verbose_name='模型檔案 (.fbx)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': '3D素材',
                'verbose_name_plural': '3D素材',
            },
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='全景圖名稱')),
                ('image', models.ImageField(upload_to='sinoVR/assets/360/', verbose_name='全景圖片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': '全景圖',
                'verbose_name_plural': '全景圖',
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='場景名稱')),
                ('description', models.TextField(blank=True, verbose_name='場景描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sinoVR.panorama', verbose_name='背景全景圖')),
            ],
            options={
                'verbose_name': 'VR場景',
                'verbose_name_plural': 'VR場景',
            },
        ),
        migrations.CreateModel(
            name='SceneObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField(default=0, verbose_name='位置 X')),
                ('position_y', models.FloatField(default=0, verbose_name='位置 Y')),
                ('position_z', models.FloatField(default=0, verbose_name='位置 Z')),
                ('rotation_x', models.FloatField(default=0, verbose_name='旋轉 X')),
                ('rotation_y', models.FloatField(default=0, verbose_name='旋轉 Y')),
                ('rotation_z', models.FloatField(default=0, verbose_name='旋轉 Z')),
                ('scale_x', models.FloatField(default=1, verbose_name='縮放 X')),
                ('scale_y', models.FloatField(default=1, verbose_name='縮放 Y')),
                ('scale_z', models.FloatField(default=1, verbose_name='縮放 Z')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinoVR.asset3d', verbose_name='3D模型')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='sinoVR.scene', verbose_name='所屬場景')),
            ],
            options={
                'verbose_name': '場景物件',
                'verbose_name_plural': '場景物件',
            },
        ),
    ]
