# Generated by Django 5.2.9 on 2026-02-04 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='字卡標題')),
                ('content', models.TextField(verbose_name='字卡內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '資訊字卡',
                'verbose_name_plural': '資訊字卡',
            },
        ),
        migrations.AlterField(
            model_name='sceneobject',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sinoVR.asset3d', verbose_name='3D模型'),
        ),
        migrations.AddField(
            model_name='sceneobject',
            name='info_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sinoVR.infocard', verbose_name='資訊字卡'),
        ),
    ]
