# Generated by Django 5.2.10 on 2026-02-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0002_infocard_alter_sceneobject_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocard',
            name='bg_color',
            field=models.CharField(default='rgba(173, 216, 230, 0.95)', max_length=50, verbose_name='背景顏色'),
        ),
        migrations.AddField(
            model_name='infocard',
            name='content_font_size',
            field=models.IntegerField(default=50, verbose_name='內容字體大小(px)'),
        ),
    ]
