# Generated by Django 5.2.10 on 2026-02-05 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0003_infocard_bg_color_infocard_content_font_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('read_at', models.DateTimeField(auto_now=True, verbose_name='閱讀時間')),
                ('info_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinoVR.infocard', verbose_name='資訊字卡')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '字卡閱讀狀態',
                'verbose_name_plural': '字卡閱讀狀態',
                'unique_together': {('user', 'info_card')},
            },
        ),
    ]
