# Generated by Django 5.2.10 on 2026-02-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0004_cardreadstatus'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardreadstatus',
            unique_together=set(),
        ),
    ]
