# Generated by Django 5.2.10 on 2026-02-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0005_alter_cardreadstatus_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset3d',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上傳者'),
        ),
        migrations.AlterField(
            model_name='sceneobject',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_objects', to='sinoVR.scene', verbose_name='所屬場景'),
        ),
    ]
