# Generated by Django 5.2.10 on 2026-02-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0006_asset3d_uploader_alter_sceneobject_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sceneobject',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sinoVR.asset3d', verbose_name='3D模型'),
        ),
    ]
