# Generated by Django 5.2.10 on 2026-02-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0007_alter_sceneobject_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset3d',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sinoVR/assets/thumbnails/', verbose_name='縮圖'),
        ),
    ]
