# Generated by Django 5.2.10 on 2026-02-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0008_asset3d_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset3d',
            name='file',
            field=models.FileField(upload_to='sinoVR/assets/3d/', verbose_name='模型檔案 (.fbx, .obj, .glb, .gltf)'),
        ),
    ]
