# Generated by Django 5.2.10 on 2026-02-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinoVR', '0009_alter_asset3d_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='動作')),
                ('target_model', models.CharField(blank=True, max_length=50, verbose_name='目標模型')),
                ('target_object_id', models.CharField(blank=True, max_length=50, verbose_name='目標ID')),
                ('target_object_str', models.CharField(blank=True, max_length=200, verbose_name='目標描述')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='詳細資訊')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者操作紀錄',
                'verbose_name_plural': '使用者操作紀錄',
                'ordering': ['-timestamp'],
            },
        ),
    ]
