# Generated by Django 5.2.9 on 2026-01-15 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=500, verbose_name='搜尋關鍵字')),
                ('index_name', models.CharField(max_length=200, verbose_name='索引名稱')),
                ('doc_id', models.CharField(max_length=200, verbose_name='文件ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='標題')),
                ('path', models.TextField(blank=True, verbose_name='檔案路徑')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='點擊時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opensearch_clicks', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '點擊記錄',
                'verbose_name_plural': '點擊記錄',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='OpenSearch__created_1e43fe_idx'), models.Index(fields=['user', '-created_at'], name='OpenSearch__user_id_1c82bc_idx'), models.Index(fields=['index_name'], name='OpenSearch__index_n_04f3aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, verbose_name='搜尋關鍵字')),
                ('indices', models.CharField(default='*', max_length=200, verbose_name='搜尋範圍')),
                ('results_count', models.IntegerField(default=0, verbose_name='結果數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='搜尋時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opensearch_searches', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '搜尋記錄',
                'verbose_name_plural': '搜尋記錄',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='OpenSearch__created_1a6745_idx'), models.Index(fields=['user', '-created_at'], name='OpenSearch__user_id_c2ffae_idx'), models.Index(fields=['query'], name='OpenSearch__query_9613b7_idx')],
            },
        ),
    ]
