# Generated by Django 5.2.9 on 2026-01-19 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenSearch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='對話標題')),
                ('indices', models.CharField(default='*', max_length=500, verbose_name='搜尋範圍')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'AI 對話',
                'verbose_name_plural': 'AI 對話',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '使用者'), ('assistant', 'AI 助理')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='內容')),
                ('keywords_used', models.CharField(blank=True, max_length=500, verbose_name='使用的關鍵字')),
                ('search_count', models.IntegerField(default=0, verbose_name='搜尋結果數量')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重試次數')),
                ('sources', models.JSONField(blank=True, default=list, verbose_name='參考來源')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示 Token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='完成 Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='OpenSearch.aichat', verbose_name='所屬對話')),
            ],
            options={
                'verbose_name': 'AI 對話訊息',
                'verbose_name_plural': 'AI 對話訊息',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aichat',
            index=models.Index(fields=['-updated_at'], name='OpenSearch__updated_e76089_idx'),
        ),
        migrations.AddIndex(
            model_name='aichat',
            index=models.Index(fields=['user', '-updated_at'], name='OpenSearch__user_id_52636f_idx'),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='OpenSearch__chat_id_06ad3b_idx'),
        ),
    ]
