"""
Django settings for CoDevStudio project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
import os
from pathlib import Path
import tempfile

# Set matplotlib config dir to a writable temp path to avoid Permission Denied in /var/www/.config
os.environ['MPLCONFIGDIR'] = os.path.join(tempfile.gettempdir(), 'matplotlib_config')
if not os.path.exists(os.environ['MPLCONFIGDIR']):
    try:
        os.makedirs(os.environ['MPLCONFIGDIR'])
    except OSError:
        pass  # Might exist or permission issue, but usually temp is writable

from .settings_local import settings as local

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = local.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =  local.DEBUG

ALLOWED_HOSTS = local.ALLOWED_HOSTS

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",

    # DRF套件
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    
    # CORS
    "corsheaders",

    # CKEditor 5
    "django_ckeditor_5",

    # 中興擴充套件
    "SinoExtension",
    "SinoTemplate",
    "SinoErrorPage",
    "BimAuth",
    "SinoAuth",
    "CourseRegistration",
    "TutorialHub",
    "SingleAuth",
    "SinoArchive",
    # CoDevStudio
    "StudioBase",
    "Home",
    "UserProfile",
    "ImageGallery",
    "DevShowcase",
    "RndRequest",
    "NewsSubscriber",
    "CarbonEstimation",
    "ProgramDbRegistry",
    "BudgetReview",
    'ERModelGenerator',
    'EVCodeSigning',
    'TeamKnowledgeHub',
    'SynonymManager',
    'PatentRegistry',
    'site360',
    'SinoFile',
    'Inlet_Design',
    'DroneReservation',
    'CODiS_WindRose_Plotter',
] + local.STAGE_INSTALLED_APPS


GEMINI_API_KEY = local.GEMINI_API_KEY
GEMINI_MODEL = local.GEMINI_MODEL

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.RemoteUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.security.SecurityMiddleware",
] + local.STAGE_MIDDLEWARES


READ_DB_LABELS = [
    *local.STAGE_READ_DB_LABELS
]
WRITE_DB_LABELS = [
    *local.STAGE_WRITE_DB_LABELS
]
MIGRATE_DB_LABELS = [
    *local.STAGE_MIGRATE_DB_LABELS
]


AUTH_SAFE_APPS = [
    'Single_Redirect',
]


SINO_AUTH_SERVICE_TOKEN = local.SINO_AUTH_SERVICE_TOKEN
SINO_AUTH_SERVICE_DOMAIN = local.SINO_AUTH_SERVICE_DOMAIN
SINO_AUTH_SERVICE_APP_PATH = local.SINO_AUTH_SERVICE_APP_PATH
ANYTHINGLLM_KEY = local.ANYTHINGLLM_KEY

ROOT_URLCONF = 'CoDevStudio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CoDevStudio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {name: cfg.to_django() for name, cfg in local.DATABASES.items()}

DATABASE_ROUTERS = [
    "CoDevStudio.routers.DataBaseRouter",
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": local.SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=1),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = "Asia/Taipei"

LANGUAGE_CODE = 'zh-hant'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = PROJECT_DIR / "static_root"
STATIC_URL = "static/"

MEDIA_ROOT = PROJECT_DIR / "media"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_PORT = 25
EMAIL_USE_SSL = False
EMAIL_HOST = local.EMAIL_HOST
EMAIL_HOST_USER = local.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = local.EMAIL_HOST_PASSWORD
SYSTEM_EMAIL = local.SYSTEM_EMAIL
NOTIFY_EMAIL_NAME = local.NOTIFY_EMAIL_NAME
NOTIFY_EMAIL = local.NOTIFY_EMAIL
AUTHENTICATION_BACKENDS = local.AUTHENTICATION_BACKENDS
EMAIL_BACKEND = local.EMAIL_BACKEND


# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link',
                      'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'],
        }
    },
    'extends': {
        'toolbar': {
            'items': ['heading', '|', 'bold', 'italic', 'link', 'underline',
                      'strikethrough', 'code', 'subscript', 'superscript', '|',
                      'bulletedList', 'numberedList', 'todoList', '|',
                      'outdent', 'indent', '|', 'blockQuote', 'insertImage',
                      'mediaEmbed', 'insertTable', 'codeBlock', 'sourceEditing'],
            'shouldNotGroupWhenFull': True
        },
        'image': {
            'toolbar': ['imageTextAlternative', 'imageStyle:alignLeft',
                        'imageStyle:alignCenter', 'imageStyle:alignRight']
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        }
    }
}
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"

# File Upload Limits
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_NUMBER_FILES = local.DATA_UPLOAD_MAX_NUMBER_FILES

# CORS Settings
CORS_ALLOWED_ORIGINS = local.CORS_ALLOWED_ORIGINS
CORS_TRUSTED_ORIGINS = local.CORS_TRUSTED_ORIGINS
CORS_ALLOW_CREDENTIALS = local.CORS_ALLOW_CREDENTIALS

# CSRF Settings
CSRF_TRUSTED_ORIGINS = local.CSRF_TRUSTED_ORIGINS

# Feature Toggles
ENABLE_CLASH_CLASSIFIER = local.ENABLE_CLASH_CLASSIFIER

# Tiered Storage Settings (Hot/Cold Data Separation)
ARCHIVE_ROOT = local.ARCHIVE_ROOT
ARCHIVE_URL = local.ARCHIVE_URL
TMP_ROOT = local.TMP_ROOT
ARCHIVE_MAX_FOLDER_SIZE = local.ARCHIVE_MAX_FOLDER_SIZE

# OpenSearch Settings
OPENSEARCH_HOST = local.OPENSEARCH_HOST
OPENSEARCH_USERNAME = local.OPENSEARCH_USERNAME
OPENSEARCH_PASSWORD = local.OPENSEARCH_PASSWORD
OPENSEARCH_VERIFY_CERTS = local.OPENSEARCH_VERIFY_CERTS
OPENSEARCH_TIMEOUT = local.OPENSEARCH_TIMEOUT
OPENSEARCH_MAX_RETRIES = local.OPENSEARCH_MAX_RETRIES
OPENSEARCH_RETRY_ON_TIMEOUT = local.OPENSEARCH_RETRY_ON_TIMEOUT
OPENSEARCH_HTTP_COMPRESS = local.OPENSEARCH_HTTP_COMPRESS
OPENSEARCH_INDEX_CACHE_TIMEOUT = local.OPENSEARCH_INDEX_CACHE_TIMEOUT