# Generated by Django 5.2.9 on 2026-01-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='請輸入主要詞彙', max_length=255, verbose_name='主詞彙')),
                ('synonym_list', models.TextField(help_text='請輸入同義詞，以逗號 (,) 分隔', verbose_name='同義詞列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '同義詞群組',
                'verbose_name_plural': '同義詞群組',
                'ordering': ['-updated_at'],
            },
        ),
    ]
