# Generated by Django 5.2.9 on 2026-01-06 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynonymManager', '0002_synonymgroup_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='關鍵字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '關鍵字',
                'verbose_name_plural': '關鍵字',
                'ordering': ['-created_at'],
            },
        ),
    ]
