# Generated by Django 5.2.9 on 2025-12-31 03:41

import EVCodeSigning.models
import EVCodeSigning.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='停用後將不再收到新申請通知', verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signing_admins', to=settings.AUTH_USER_MODEL, verbose_name='設定者')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signing_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '簽章管理員',
                'verbose_name_plural': '簽章管理員',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='簡述此次簽章申請的內容', max_length=200, verbose_name='申請標題')),
                ('description', models.TextField(help_text='請詳細說明簽章需求、用途及相關資訊', verbose_name='申請說明')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('completed', '已完成'), ('rejected', '已退回')], default='pending', max_length=20, verbose_name='狀態')),
                ('reject_reason', models.TextField(blank=True, help_text='當申請被退回時，管理員需填寫此欄位', verbose_name='退回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請人')),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to='EVCodeSigning.signingadmin', verbose_name='處理管理員')),
            ],
            options={
                'verbose_name': '簽章申請',
                'verbose_name_plural': '簽章申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=EVCodeSigning.models.signing_file_upload_path, validators=[EVCodeSigning.validators.validate_signing_file], verbose_name='原始檔案')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to=EVCodeSigning.models.signed_file_upload_path, verbose_name='簽章後檔案')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='檔案大小（bytes）')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='簽章時間')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='EVCodeSigning.signingrequest', verbose_name='所屬申請')),
            ],
            options={
                'verbose_name': '簽章檔案',
                'verbose_name_plural': '簽章檔案',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
