# Generated by Django 5.2.9 on 2026-01-08 06:46

import EVCodeSigning.models
import EVCodeSigning.validators
import SinoFile.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVCodeSigning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingfile',
            name='original_file',
            field=SinoFile.fields.SinoFileField(upload_to=EVCodeSigning.models.signing_file_upload_path, validators=[EVCodeSigning.validators.validate_signing_file], verbose_name='原始檔案'),
        ),
        migrations.AlterField(
            model_name='signingfile',
            name='signed_file',
            field=SinoFile.fields.SinoFileField(blank=True, null=True, upload_to=EVCodeSigning.models.signed_file_upload_path, verbose_name='簽章後檔案'),
        ),
    ]
