# Generated by Django 5.2.9 on 2025-12-12 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='分類代碼')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '主要分類',
                'verbose_name_plural': '主要分類',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ComponentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=20, unique=True, verbose_name='項次')),
                ('work_item', models.CharField(max_length=200, verbose_name='工作項目')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='單位')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='說明')),
                ('default_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='預設數量')),
                ('carbon_before', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='減碳前單位碳排量 (kgCO2e/單位)')),
                ('carbon_after', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='減碳後單位碳排量 (kgCO2e/單位)')),
                ('cost_before', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='減碳前單位造價費用 (元/單位)')),
                ('cost_after', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='減碳後單位造價費用 (元/單位)')),
                ('carbon_unit', models.CharField(blank=True, max_length=50, verbose_name='碳排單位')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('reference', models.TextField(blank=True, verbose_name='說明(出處/連結)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CarbonEstimation.maincategory', verbose_name='所屬分類')),
            ],
            options={
                'verbose_name': '組件項目',
                'verbose_name_plural': '組件項目',
                'ordering': ['category__order', 'category__code', 'order', 'item_no'],
            },
        ),
    ]
