# Generated by Django 5.2.9 on 2025-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEstimation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentitem',
            name='level',
            field=models.IntegerField(default=3, help_text="1=工程大項(如'一'), 2=中項(如'一.1'), 3=細項(如'一.1.1')", verbose_name='階層'),
        ),
    ]
