# Generated by Django 5.2.9 on 2025-12-12 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEstimation', '0002_componentitem_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, verbose_name='計畫編號')),
                ('project_name', models.CharField(max_length=200, verbose_name='計畫名稱')),
                ('scenario_name', models.CharField(max_length=200, verbose_name='方案名稱')),
                ('description', models.TextField(blank=True, verbose_name='方案說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborative_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='共同編輯人')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
            ],
            options={
                'verbose_name': '方案',
                'verbose_name_plural': '方案',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='數量')),
                ('last_saved_at', models.DateTimeField(auto_now=True, verbose_name='最後儲存時間')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarbonEstimation.maincategory', verbose_name='所屬分類')),
                ('component_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarbonEstimation.componentitem', verbose_name='組件項目')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='CarbonEstimation.scenario', verbose_name='所屬方案')),
            ],
            options={
                'verbose_name': '方案數據',
                'verbose_name_plural': '方案數據',
            },
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['project_number'], name='CarbonEstim_project_42176c_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['creator'], name='CarbonEstim_creator_f3d242_idx'),
        ),
        migrations.AddIndex(
            model_name='scenariodata',
            index=models.Index(fields=['scenario', 'category'], name='CarbonEstim_scenari_f3bf47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scenariodata',
            unique_together={('scenario', 'component_item')},
        ),
    ]
