# Generated by Django 5.2.9 on 2025-12-19 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEstimation', '0004_alter_scenario_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
    ]
