# Generated by Django 5.2.9 on 2026-01-20 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEstimation', '0005_alter_componentitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='分類代碼')),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '斷面分類',
                'verbose_name_plural': '斷面分類',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='project_phase',
            field=models.CharField(choices=[('feasibility', '可評階段'), ('comprehensive', '綜規及基設階段')], default='comprehensive', max_length=20, verbose_name='工程階段'),
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_item', models.CharField(max_length=200, verbose_name='工作項目')),
                ('unit', models.CharField(default='m2', max_length=20, verbose_name='單位')),
                ('carbon_per_unit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='單位面積碳排 (kgCO2e/m2)')),
                ('description', models.TextField(blank=True, verbose_name='說明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CarbonEstimation.sectioncategory', verbose_name='所屬分類')),
            ],
            options={
                'verbose_name': '斷面項目',
                'verbose_name_plural': '斷面項目',
                'ordering': ['category__order', 'category__code', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='數量')),
                ('last_saved_at', models.DateTimeField(auto_now=True, verbose_name='最後儲存時間')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_data', to='CarbonEstimation.scenario', verbose_name='所屬方案')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarbonEstimation.sectioncategory', verbose_name='所屬分類')),
                ('section_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarbonEstimation.sectionitem', verbose_name='斷面項目')),
            ],
            options={
                'verbose_name': '方案斷面數據',
                'verbose_name_plural': '方案斷面數據',
                'indexes': [models.Index(fields=['scenario', 'category'], name='CarbonEstim_scenari_8c411e_idx')],
                'unique_together': {('scenario', 'section_item')},
            },
        ),
    ]
