# Generated by Django 5.2.9 on 2026-01-20 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEstimation', '0006_sectioncategory_scenario_project_phase_sectionitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
            preserve_default=False,
        ),
    ]
