# Generated by Django 5.2.9 on 2026-01-20 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEstimation', '0007_alter_scenario_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='隱藏時間'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='隱藏者'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='一般使用者刪除時會標記為隱藏，僅管理員可見', verbose_name='已隱藏'),
        ),
    ]
