# Generated by Django 5.2.10 on 2026-02-25 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEstimation', '0008_scenario_hidden_at_scenario_hidden_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='hidden_at',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='hidden_by',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='project_phase',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='建立者'),
        ),
        migrations.DeleteModel(
            name='ScenarioSectionData',
        ),
        migrations.DeleteModel(
            name='SectionCategory',
        ),
        migrations.DeleteModel(
            name='SectionItem',
        ),
    ]
