# Generated by Django 5.2.10 on 2026-02-03 03:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名稱')),
                ('points', models.JSONField(help_text='JSON陣列，包含8個點的座標，格式: [[x1,y1], [x2,y2], ...]', verbose_name='控制點座標')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '凸字形圖形',
                'verbose_name_plural': '凸字形圖形',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('3_circle', '3心圓'), ('4_circle', '4心圓')], max_length=20, verbose_name='配置類型')),
                ('total_area', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='總面積')),
                ('is_optimized', models.BooleanField(default=True, verbose_name='是否為優化結果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='CircleOptimizer.shape', verbose_name='圖形')),
            ],
            options={
                'verbose_name': '圓配置',
                'verbose_name_plural': '圓配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='圓索引')),
                ('center_x', models.FloatField(verbose_name='圓心X座標')),
                ('center_y', models.FloatField(verbose_name='圓心Y座標')),
                ('radius', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='半徑')),
                ('arc_length', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='弧長')),
                ('start_angle', models.FloatField(help_text='以度為單位，0-360', verbose_name='起始角度（度）')),
                ('end_angle', models.FloatField(help_text='以度為單位，0-360', verbose_name='結束角度（度）')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circles', to='CircleOptimizer.circleconfig', verbose_name='圓配置')),
            ],
            options={
                'verbose_name': '圓',
                'verbose_name_plural': '圓',
                'ordering': ['circle_index'],
                'unique_together': {('config', 'circle_index')},
            },
        ),
    ]
