# Generated by Django 5.2.8 on 2026-02-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CircleOptimizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circleconfig',
            options={'ordering': ['-created_at'], 'verbose_name': '隧道斷面配置', 'verbose_name_plural': '隧道斷面配置'},
        ),
        migrations.AlterModelOptions(
            name='shape',
            options={'ordering': ['-created_at'], 'verbose_name': '隧道斷面圖形', 'verbose_name_plural': '隧道斷面圖形'},
        ),
    ]
